RackHD/RackHD

- example/bin/monorail_rack
- example/roles/repos/tasks/main.yml
Matching to documentation work - adding in mechanisms to render api docs from the on-http repository
> Render apidocs

- example/roles/repos/tasks/main.yml
Include EFI images
@RackHD/corecommitters @RackHD/rackhd_dev
> Rename ipxe images to match on-dhcp-proxy bootfile name

- example/roles/repos/tasks/main.yml
This should fix any possible permissions issues with copying down the static files. 
resolves #11
> removed sudo call when making common dir

- example/README.md
> fixing broken link, resolves #25

- .gitignore
- example/README.md
- example/Vagrantfile
- example/samples/centos_iso_boot.json
- example/samples/centos_iso_kvm_boot.json
- example/samples/full_centos_mirror_boot.json
updating README instructions to working through the process of downloading a CentOS ISO and how to run a workflow that installs that OS from the provided ISO.
During this setup, I opened #35 and #36 with issues related to this process.
> Install centos iso

- test/modules/amqp.py
- test/tests/amqp_tests.py
@RackHD/corecommitters @keedya @tannoa2 @uppalk1 @zyoung51 @benbp
> Add AMQP connection timeout

- example/README.md
A minor change to add VirtualBox in 'PRE-REQS / SCRIPT EXPECTATIONS' section.
> A minor change to add VirtualBox in 'PRE-REQS / SCRIPT EXPECTATIONS'

- packer/ansible/roles/monorail/files/monorail.json
from on-core
to be merged after https://github.com/RackHD/on-core/pull/51 is merged
> updating to match log-leveling PR

- test/modules/obm.py
- test/run.py
- test/tests/config_tests.py
- test/tests/nodes_tests.py
- test/tests/obm_tests.py
@RackHD/corecommitters @jlongever @zyoung51 @keedya @tannoa2
> Validate OBM APIs and Node Patch API 

- test/tests/lookups_tests.py
@jlongever @zyoung51 @uppalk1 @RackHD/corecommitters @keedya
> Added Lookups test

- test/run.py
- test/tests/workflowTasks_tests.py
- test/tests/workflows_tests.py
@RackHD/corecommitters @zyoung51 @keedya @uppalk1
> Added tests for the WORKFLOWTASKS and the WORKFLOWS

- test/config/settings.py
- test/modules/obm.py
- test/tests/amqp_tests.py
- test/tests/nodes_tests.py
- test/tests/workflows_tests.py
- Discovery graph completion checks.
- AMQP per node checks.
- Added AMQP concurrency using python threads.
- Temporarily remove workflow post test
@RackHD/corecommitters @tannoa2 @zyoung51 @uppalk1 @keedya
> AMQP test enhancements

- test/README.md
- test/config/settings.py
- test/requirements.txt
Add on-http pypi to pip requirements file, remove apt-get dependency.
Fix BMC credentials prompt
@RackHD/corecommitters @zyoung51 @uppalk1 @tannoa2 @tldavies
> test README.md cleanup

- test/tests/workflows_tests.py
Fixes random workflow test failure.
@RackHD/corecommitters @zyoung51 @keedya @uppalk1
> Listen on AMQP for noop-example graph finish event.

- .gitmodules
adding submodule after resetting repository to reflect ancilliary
tools for RackHD project. Partial resolution for
https://github.com/RackHD/RackHD/issues/33
> adding on-tools repo to rackhd

- example/Vagrantfile
- example/bin/monorail_rack
- example/config/monorail_rack.cfg.example
- Add bridge interface variable
- Add workspace and target repo variable
@RackHD/corecommitters @DavidjohnBlodgett @keedya @zyoung51 @uppalk1 @tannoa2
> Add vagrant example configuration variables.

- packer/ansible/roles/monorail/tasks/main.yml
Stepping forward the modules to rebuild a latest vagrant instance that leverages the most recent code.
resolves https://github.com/RackHD/RackHD/issues/96
believed will also resolve https://github.com/RackHD/RackHD/issues/94
> Step forward submodules, packer rebuild

- test/tests/api/v2_0/__init__.py
- test/tests/api/v2_0/config_tests.py
@brianparry @abildw @dalebremner @srinia6
> Added functional test for api/2.0/config

- test/requirements.txt
@dalebremner @brianparry @abildw @jlongever @srinia6
> added on-http-api-2.0 to requirements.txt for tests

- test/tests/api/v2_0/__init__.py
- test/tests/api/v2_0/nodes_tests.py
@abildw @brianparry @srinia6 @dalebremner @RackHD/corecommitters
> Added functional tests for node routes in the 2.0 api

- test/tests/api/v2_0/__init__.py
- test/tests/api/v2_0/catalogs_tests.py
@dalebremner @brianparry @geoff-reid @abildw @RackHD/corecommitters
> Catalogs functional test

- test/tests/api/v2_0/__init__.py
- test/tests/api/v2_0/obm_settings.py
- test/tests/api/v2_0/obm_tests.py
> Functional tests for 2.0 API OBM

- test/tests/api/v2_0/__init__.py
- test/tests/api/v2_0/pollers_tests.py
Depends on https://github.com/RackHD/on-http/pull/173
> Add tests for /api/2.0/pollers route

- example/README.md
- packer/ansible/rackhd_local.yml
- packer/ansible/roles/integrationtest/tasks/main.yml
- packer/ansible/roles/swagger/tasks/main.yml
- scripts/link_install_locally.bash
adding in python virtualenv, maven and swagger components to VM for local dev efforts
> python, maven and swagger additions

- test/config/auth.py
- test/modules/auth.py
- test/requirements.txt
Requires https://github.com/RackHD/on-http/pull/178
> Update for swagger authn/authz changes

- test/tests/api/v1_1/nodes_tests.py
- test/tests/api/v1_1/workflowTasks_tests.py
- test/tests/api/v2_0/nodes_tests.py
@RackHD/corecommitters @uppalk1 @tannoa2 @keedya @geoff-reid @tannoa2
> Handle workflow status before issuing command with timeout

- test/tests/api/v2_0/nodes_tests.py
Possible fix for https://github.com/RackHD/RackHD/issues/151
> Fix for delete workflow test failures

- docker/files/Dockerfile
- packer/ansible/roles/images/tasks/main.yml
related PR:
https://github.com/RackHD/on-imagebuilder/pull/32
https://github.com/RackHD/on-dhcp-proxy/pull/30
@RackHD/rackhd_dev @RackHD/corecommitters
> Fetch undionly.kpxe from ipxe

- test/benchmark.py
- test/benchmark/__init__.py
- test/benchmark/api_v1_1/__init__.py
- test/benchmark/api_v1_1/bootstrap_tests.py
- test/benchmark/api_v1_1/discovery_tests.py
- test/benchmark/api_v1_1/poller_tests.py
- test/benchmark/api_v2_0/__init__.py
- test/benchmark/api_v2_0/bootstrap_tests.py
- test/benchmark/api_v2_0/discovery_tests.py
- test/benchmark/api_v2_0/poller_tests.py
- test/benchmark/utils/ansible/collect_data.yml
- test/benchmark/utils/ansible/files/atoprc
- test/benchmark/utils/ansible/files/collect_data.sh
- test/benchmark/utils/ansible/files/db_disk.sh
- test/benchmark/utils/ansible/files/rsync
- test/benchmark/utils/ansible/files/rsyncd.conf
- test/benchmark/utils/ansible/group_vars/benchmark.json
- test/benchmark/utils/ansible/setup_env.yml
- test/benchmark/utils/ansible/start_daemon.yml
- test/benchmark/utils/ansible/vars/setup.yml
- test/benchmark/utils/ansible_control.py
- test/benchmark/utils/case_recorder.py
- test/benchmark/utils/parser.py
- test/config/benchmark_config.py
- test/config/settings.py
- test/requirements.txt
- test/tests/api/v1_1/poller_tests.py
This PR implements the process of running benchmark test.
https://github.com/RackHD/RackHD/wiki/proposal-footprint-benchmarks
Users issue the test by
```
~/src/RackHD/test$ python benchmark.py
```
To run the test in API v2, please use "--api_version=2". (cases in api v2 has not been implemented yet)
API v1.1 is used by default.
The log data is in ~/benchmark/<timestamp>
Related info will be added to README later.
The first time users run this script, he will be asked about user/pwd in the test machine (local) and RackHD. This is used in Ansible to setup test environment both in local and RackHD.
It will include several typical footprint scenarios (like running poller, discovery and bootstrap), and aims to get footprint data from several tools (atop and mongo shell) and display the result. …
> Footprint benchmark initial checkin

- test/tests/api/v2_0/__init__.py
- test/tests/api/v2_0/catalogs_tests.py
- test/tests/api/v2_0/config_tests.py
- test/tests/api/v2_0/workflowTasks_tests.py
- test/tests/api/v2_0/workflows_tests.py
@RackHD/corecommitters @srinia6 @abildw @geoff-reid
> Workflows 2.0 API Functional Tests

- packer/ansible/roles/images/tasks/main.yml
@RackHD/corecommitters @rolandpoulter @VulpesArtificem @tldavies 
relates to:
https://github.com/RackHD/on-imagebuilder/pull/31
https://github.com/RackHD/on-tasks/pull/148
https://github.com/RackHD/docs/pull/257
> updated packer with new static file names

- test/tests/api/v2_0/__init__.py
- test/tests/api/v2_0/nodes_tests.py
- test/tests/api/v2_0/tags_tests.py
*Add test for masterDelTag option in nodes_tests.py
*Add tests for /tags API in tags_tests.py
*update __init__.py to import new test file (tags_tests.py)
Note : There is an intermittent issue being tracked in pivotal tracker which is being debugged
https://www.pivotaltracker.com/projects/1492890/stories/117246337
> Create functional tests for node tags APIs 

- packer/ansible/roles/images/tasks/main.yml
> Revert "updated packer with new static file names"

- test/config/redfish1_0_config.py
- test/modules/redfish_auth.py
- test/tests/api/redfish_1_0/__init__.py
- test/tests/api/redfish_1_0/registry_tests.py
- test/tests/api/redfish_1_0/schema_tests.py
- test/tests/api/redfish_1_0/session_service_tests.py
@RackHD/corecommitters @uppalk1 @tannoa2 @keedya 
Depends on: https://github.com/RackHD/on-http/pull/244
> [redfish] Add schema, registry and session-service functional tests

- test/config/redfish1_0_config.py
- test/config/settings.py
- test/modules/httpd.py
- test/modules/worker.py
- test/run.py
- test/tests/api/redfish_1_0/__init__.py
- test/tests/api/redfish_1_0/event_service_tests.py
- test/tests/api/v1_1/amqp_tests.py
Added Redfish event service functional tests
Added simple httpd server to test webhook functionality of event services
Added continuous run option to worker class
Added timeout assertion for worker task
@RackHD/corecommitters @zyoung51 @uppalk1 @tannoa2 @keedya @geoff-reid
> [redfish] Add EventService Functional Tests

- example/README.md
- example/samples/noop_body.json
leftover work from https://github.com/RackHD/RackHD/issues/33
and requested in https://github.com/RackHD/on-http/pull/253#issuecomment-215444722
@RackHD/corecommitters @zyoung51 @heckj 
this has been tested.
> updated instructions for CentOS after on-tools reorg

- test/tests/api/v2_0/pollers_tests.py
Required for https://github.com/RackHD/on-core/pull/127
> Remove password from poller.config check

- test/tests/api/v2_0/__init__.py
- test/tests/api/v2_0/schema_tests.py
@RackHD/corecommitters @zyoung51 @srinia6 @geoff-reid @abildw
> API 2.0 Schemas Functional Tests

- test/tests/api/v2_0/__init__.py
- test/tests/api/v2_0/skupack_tests.py
@brianparry @dalebremner @abildw @zyoung51 @jlongever @keedya @uppalk1 @amymullins
> Sku pack test

- test/benchmark/api_v1_1/poller_tests.py
- test/benchmark/utils/ansible/setup_env.yml
- test/benchmark/utils/parser.py
1. Added in  setup_env.yml to clone html files from on-tools repo
2. added in parser.py to copy html files to log dir
This PR depends on https://github.com/RackHD/RackHD/pull/212 and https://github.com/RackHD/on-tools/pull/22
@RackHD/corecommitters @iceiilin @WangWinson @wuy1
> Code to copy html file to log directory. Change includes:

- test/README.md
- test/run.py
- test/tests/api/redfish_1_0/__init__.py
- test/tests/api/v1_1/__init__.py
- test/tests/api/v1_1/os_install_tests.py
- test/tests/api/v2_0/__init__.py
Pass --group option:
`--group=regression-tests`
`--group=smoke-tests`
With no group option specified defaults to smoke-tests
@RackHD/corecommitters @uppalk1 @zyoung51 @keedya @tannoa2
> Create smoke-test and regression test groups

- test/tests/api/v1_1/workflows_tests.py
- Fixes error reporting on task timeout error.
@RackHD/corecommitters @uppalk1 @tannoa2 @zyoung51 @keedya
> Handle workflow task timeout failure status

- test/tests/api/v1_1/workflows_tests.py
@RackHD/corecommitters @zyoung51 @uppalk1 @tannoa2 @keedya
> Fix reference to tasks in post workflow method

- packer/ansible/rackhd_local.yml
- packer/ansible/rackhd_package.yml
- packer/ansible/roles/postgresql/tasks/main.yml
@RackHD/corecommitters @zyoung51 @uppalk1 @tannoa2 @keedya
> Add and setup PostgreSQL backend services

- .gitmodules
- docker/Vagrantfile
- docker/docker-compose.yml
- docker/monorail/config.json
- scripts/clean_all.bash
- scripts/link_install_locally.bash
- scripts/reset_submodules.bash
* Adds on-wss submodule
* Forward port 9100 from docker vm to host
* Moves dhcpd.leases mount from taskgraph to dhcp-proxy
* Fixes for docker/monorail/config.json
> Updates RackHD docker example to include on-wss module

- example/README.md
- packer/ansible/roles/monorail/files/config.json
- packer/scripts/firstuser.sh
- packer/template-packages.json
- packer/template-ubuntu-14.04.json
- packer/template-ubuntu-16.04.json
- Add script to create first user for 2.0 and redfish API authentication.  Uses the localhost exception method to generate the first user: https://docs.mongodb.com/manual/core/security-users/#localhost-exception 
@RackHD/corecommitters @zyoung51 @tannoa2 @uppalk1 @keedya
> Enable auth and create first user in packer build

- test/config/config.ini
- test/tests/api/v1_1/os_install_tests.py
@RackHD/corecommitters @zyoung51 @uppalk1 @keedya @tannoa2 @brianparry
> Default to base OS repo path in config

- test/tests/api/v2_0/skupack_tests.py
@RackHD/corecommitters @BillyAbildgaard @dalebremner @srinia6
> Add templates and profiles to skupack test validation.

- test/tests/api/v1_1/nodes_tests.py
- test/tests/api/v1_1/obm_settings.py
- test/tests/api/v2_0/lookups_tests.py
- test/tests/api/v2_0/nodes_tests.py
- test/tests/api/v2_0/obm_settings.py
- test/tests/api/v2_0/obm_tests.py
- test/tests/api/v2_0/workflows_tests.py
@RackHD/corecommitters @srinia6 @BillyAbildgaard @zyoung51 @jlongever 
Dependent on:
RackHD/on-core#164
RackHD/on-http#312
RackHD/on-tasks#243
RackHD/on-http#348
* Requires PyPI update of on-http client libraries
> Functional test changes for OBM refactoring

- test/benchmark/utils/parser.py
add summary into graph
@pengz1 @iceiilin @WangWinson
> add summary into graph

- packer/ansible/roles/isc-dhcp-server/files/dhcpd.conf
- test/tests/api/v1_1/os_install_tests.py
- Required in Ubuntu netboot installtion
@RackHD/corecommitters @zyoung51 @brianparry @jlongever
> Add Domain name and routers options to DHCP

- test/tests/api/v1_1/os_install_tests.py
> Change Graph.InstallEsx to Graph.InstallESXi

- test/tests/api/v1_1/os_install_tests.py
@RackHD/doccommitters @jlongever @keedya @zyoung51 @jlongever
> Edit the workflow for the SUSE install test

- scripts/reset_submodules.bash
missing from submodule/reset update script
> added missing on-imagebuilder repo

- test/tests/api/v2_0/obm_settings.py
@RackHD/corecommitters @keedya @dalebremner @BillyAbildgaard
> Change OBM test to accept new OBM view

- example/samples/install_photon_os_payload_full.json
- example/samples/install_photon_os_payload_minimal.json
Add minimal and full exmaple options of PhotonOS
@yyscamper @cgx027
> Add exmaple options of PhotonOS

- scripts/link_install_locally.bash
@yyscamper @WangWinson review please? :-)
> adding npm taskdoc generation to update script

- example/README.md
- example/Vagrantfile
- example/samples/full_centos_mirror_boot.json
- example/samples/vQuanta_d51_sku.json
- example/samples/vQuanta_install_centos.json
- example/samples/vQuanta_install_coreos.json
- virtual SKU definitions added
- example CentOS install workflow for SKU
- updated README with InfraSim how to details
> update example/ to use InfraSim

- example/samples/install_esx_payload_full.json
* add ntpServers
* support MAC address for device included in networkDevices
* support MAC address for uplinks included in switchDevices
> revise esxi full payload

- test/tests/api/v2_0/skupack_tests.py
Check if sku pack info is deleted from Skus (get-sku) after a delete sku pack
> Delete-sku-pack minor enhancement

- packer/ansible/roles/remoterepos/tasks/main.yml
Thanks Jason (and sorry for the pain of missing this)
> adding sudo for package install

- test/README.md
- test/benchmark/api_v1_1_tests.py
- test/benchmark/utils/ansible_control.py
- test/config/benchmark_config.py
Update benchmark test cases to be accommodated with the latest code in test repo.
1. use rackhd ssh info in config.ini instead of environmental variables
2. use post_workflow method in workflows_tests.py and remove private functions in benchmark bootstrap class.
@jlongever @cgx027
> modify benchmark cases to use common config.ini and workflow methods

- packer/README.md
- packer/ansible/roles/remoterepos/tasks/main.yml
- packer/template-ubuntu-14.04.json
- updating packer readme for local builds and notes on accessing vagrant boxes locally 
- workaround for https://github.com/RackHD/RackHD/issues/357
> Local packer

- packer/scripts/firstuser.sh
- resolves https://github.com/RackHD/RackHD/issues/372
- shuts down services that were started in firstuser.sh script at end
of processing
> workaround for packer build hang

- packer/ansible/roles/monorail/files/config.json
- test/config/api2_0_config.py
- test/modules/auth2_0.py
- test/tests/api/v2_0/__init__.py
- test/tests/api/v2_0/skupack_tests.py
- test/tests/api/v2_0/users_tests.py
Add functional tests for authentication
- Create users
- modify users
- remove users
- Test Privileges
http://rackhd.readthedocs.io/en/latest/tutorials/vagrant.html needs to be modified. It will be tracked in a different story and PR
> Add functional tests for authentication

- test/tests/api/v1_1/os_install_tests.py
@brianparry @jlongever @tannoa2 @dalebremner @zyoung51
> Fix typo in windows installation

- test/tests/api/v2_0/__init__.py
- test/tests/api/v2_0/swagger_tests.py
* Add tags test to prevent problems with Swagger UI rendering
> Add swagger object functional test

- test/tests/api/v2_0/workflows_tests.py
dependent on RackHD/on-http#443
Jenkins: depends on https://github.com/RackHD/on-http/pull/443
Fix for build failures on https://github.com/RackHD/on-http/pull/443 
@brianparry @BillyAbildgaard @dalebremner @keedya @geoff-reid @RackHD/corecommitters
> Functional test fix for PR 443

- README.md
Note: Copyrights and related details *do not* need to be proactively changed. We can change them as we would any other copyright update - when we edit the files as we go forward.
Also I didn't include the email address change from rackhd@emc.com to rackhd@dell.com because the email alias hasn't yet been migrated. There's a ticket with IT where I'm tracking that transition, and I'll update relevant docs and links afterwards.
> updates for Day 1 of EMC -> Dell merger

- packer/ansible/roles/monorail/files/config.json
Change includes:
(1) Remove the duplicated minLogLevel
(2) Change minLogLevel to 0, so that the debug message can also be printed. This will help to identify issue in Jenkin CI (The Jenkins uses this config in testing) and customer reported bugs.
@heckj @RackHD/corecommitters @jlongever   @panpan0000 @PengTian0 @changev
> remove duplicated minLogLevel & change minLogLevel to 0

- test/tests/api/v2_0/nodes_tests.py
@RackHD/corecommitters @BillyAbildgaard @srinia6 @dalebremner @keedya
> Added functional tests for GET & PUT api/2.0/nodes/:id/obm

- test/tests/api/v2_0/catalogs_tests.py
@RackHD/corecommitters @srinia6 @dalebremner @keedya @BillyAbildgaard @zyoung51
> Add data validation to catalogs funtcional tests

- example/samples/install_windows_payload_full.json
- example/samples/install_windows_payload_minimal.json
* remove completionUri from sample payloads
> Replace completionUri with notification

- test/tests/api/v1_1/nodes_tests.py
- Log the entire workflow task data on a node discovery task failure.
- ACK message if graph and route ID's match.
@RackHD/corecommitters @changev @panpan0000
> Log node discovery task failure

- packer/scripts/firstuser.sh
resolves  https://github.com/RackHD/RackHD/issues/407
@heckj @RackHD/corecommitters @jlongever @amymullins @zyoung51 @uppalk1 
here is a link to jenkins job with this fix:
http://rackhdci.lss.emc.com/job/vagrant-build/77/
> fix packer build issue

- test/tests/api/v1_1/os_install_tests.py
@RackHD/corecommitters @srinia6 @BillyAbildgaard @geoff-reid @keedya
> Added CoreOS installation test

- test/tests/api/redfish_1_0/systems_tests.py
Needed for: https://github.com/RackHD/on-http/pull/468
> [redfish] Remove unused fields

- example/samples/install_coreos_payload_minimal.json
- test/config/config.ini
- test/tests/api/v1_1/os_install_tests.py
@RackHD/corecommitters @srinia6 @geoff-reid @BillyAbildgaard @jlongever
> Get CoreOS minimal payload from sample file

- example/samples/centos_iso_boot.json
- example/samples/centos_iso_kvm_boot.json
- example/samples/full_centos_mirror_boot.json
- example/samples/install_ubuntu_payload_iso_full.json
- example/samples/install_ubuntu_payload_iso_minimal.json
- example/samples/vQuanta_default_install_workflow.json
- example/samples/vQuanta_default_workflow.json
Change api.server to file.server to adjust with optional external static file server
@cgx027 @lanchongyizu
> Replace api.server with file.server in samples

- example/samples/install_esx_payload_full.json
@RackHD/corecommitters @cgx027 @zyoung51 @iceiilin @pengz1
> add esxSwitchName in esxi full payload example

- docker/README.md
- docker/Vagrantfile
- docker/create_pxe_vm.bash
- docker/docker-compose.yml
- docker/docker_vm_up.bash
- docker/export_docker_host.bash
- docker/monorail/config.json
* Fixes `docker-compose.yml` to include additional `on-tasks` base image.
* Changes Vagrantfile to use a more recent version of Docker on Ubuntu.
* Updates README with new Mac OS X installation instructions.
> Fixes RackHD/docker for Mac

- test/tests/api/v1_1/os_install_tests.py
- test/tests/api/v2_0/nodes_tests.py
- Pass `acpi=off` for Platform-A ESXi install test
- Added 2.0 workflow API in 2.0 node discovery test group
- Fixed API 2.0 test order (incorrect dependent group name)
@brianparry @geoff-reid 
Jenkins: depends on https://github.com/RackHD/on-http/pull/491
Jenkins: depends on https://github.com/RackHD/on-tasks/pull/355
> ESXi install and 2.0 node discovery test updates

- test/tests/api/v1_1/os_install_tests.py
@keedya @tannoa2 @uppalk1 @RackHD/corecommitters
> modify centOS install tests to read payload files.

- example/samples/install_centos_payload_minimal.json
- test/tests/api/v1_1/os_install_tests.py
@keedya @tannoa2 @uppalk1 @RackHD/corecommitters
> Remove extra parameters from centOS minimal install

- example/samples/install_centos_payload_full.json
- example/samples/install_centos_payload_minimal.json
- test/tests/api/v1_1/os_install_tests.py
@keedya @tannoa2 @uppalk1 @RackHD/corecommitters
> add centos 7 mas payload install tests

- debian/control
- debian/postinst
- debian/rackhd.init
1.  Remove the "--force". Because ubuntu 16.04 doesn't support the option.
2.  Enable rackhd start on startup
3.  Start on-xxx service only when the service is not running
@yyscamper @anhou @panpan0000
> enable rackhd on ubuntu 16.04

- example/samples/install_windows_payload_full.json
- test/tests/api/v1_1/os_install_tests.py
- Update max payload for windows server 2012 installation
> OS Install Regression test enhancements for Windows OS

- test/tests/api/v1_1/os_install_tests.py
It's related with https://github.com/RackHD/on-taskgraph/pull/183.
@RackHD/corecommitters @panpan0000 @iceiilin
> remove validate-ssh from payload for os_install_tests

- example/samples/install_esx_payload_full.json
- test/tests/api/v1_1/os_install_tests.py
> ESXi 6.0 and 5.5 min and max payload tests

- example/samples/install_coreos_payload_full.json
creating max payload file for CoreOS.  My next story is to refine some options such as network devices by testing on real hardware.
@srinia6 @uppalk1 @tannoa2 @geoff-reid @dalebremner @keedya
> CoreOS max payload

- example/samples/install_windows_payload_full.json
.....to let the ping function test the new static IP
> Include firewallDisable in options 

- test/fit_tests/deploy/rackhd_source_install.py
- test/fit_tests/deploy/rackhd_stack_init.py
These updates cleanup the stack initialization script to lessen the output to the console during the  run and check for a few more errors when installing sku packs.
I tested the changes against multiple stacks - doing both negative/positive tests to verify the updates.
If output logs are needed, I can attach them.
> fit_tests - fix the rackhd_stack_init script which sets up rackhd on physical stacks

- test/tests/api/v1_1/os_install_tests.py
@keedya @tannoa2 @uppalk1 @brianparry
> add longer timeout to test_link_up for OS installs

- docker/README.md
- docker/docker-compose-mini.yml
sometimes, people want a mini try. because it's very very slow for docker pull in China.
run by docker-compose -f docker-compose-mini.yml  up
> Docker mini compose file

- packer/ansible/roles/snmptool/tasks/main.yml
related PR for Docker: https://github.com/RackHD/on-taskgraph/pull/192
Signed-off-by: Joe Heck <heckj@mac.com>
> adding mib downloads to vagrant image

- test/tests/api/v1_1/__init__.py
- test/tests/api/v1_1/decomission_node_tests.py
- test/tests/api/v1_1/workflows_tests.py
Test includes:
- set bmc credentials using rackhd workflow
- decommission node includs:
-- remove selected bmc users
-- erase disk
> Add decommission test to regression group

- test/README.md
- test/common/fit_common.py
- test/config/global_config.json
- test/deploy/os_ova_install.py
- test/run_tests.py
> RAC-267 Multiple OVA installation per stack

- test/common/api_utils.py
* Created  file common/api-utils.py
* Added method api_node_select_argsList()
* Added method api_node_select()
* Ccrrected if chain in common/fit_common -> restful()
* Remove sys(255) call as suggested by PR
> RAC-805 - methods to use within scripts for checking the test bed

- test/tests/compute/test_rackhd11_computenode_pollers.py
- test/tests/compute/test_rackhd20_computenode_pollers.py
This test is failing in the ReackHD/RackHD repo. This PR has the corrections that were originally checked into the Onrack2 repo by Erika.
> Bugfix for computenode_pollers tests

- test/tests/rackhd20/test_rackhd20_api_pollers.py
This is a correction for the pollers test. 
> bugfix tests/rackhd20/test_rackhd20_api_pollers.py

- test/tests/redfish10/test_redfish10_api_eventservice.py
Revised response codes in this FIT test to correct values.
> bugfix tests/redfish10/test_redfish10_api_eventservice.py

- packer/ansible/roles/rackhd-builds/tasks/main.yml
rackhd-mirror is the test mirror of rackhd, it should not appear in prod code.
> change wrong 'rackhd-mirror' to rackhd

- packer/HWIMO-BUILD
- packer/template-ubuntu-14.04.json
- packer/template-ubuntu-16.04.json
This feature was missing in some PR.
Now added.
@panpan0000 @PengTian0 
--------------------------------------------------------
Test job successed
http://rackhdci.lss.emc.com/job/BuildRelease/job/Build/job/vagrant-build/109/
> bugfix: modify packer build to use rackhd_version parameter

- test/deploy/rackhd_stack_init.py
the original PR https://github.com/RackHD/RackHD/pull/560 has a obvious typo.
I ask CC's favour to merge https://github.com/RackHD/RackHD/pull/560 in , but I should be in charged of to fix this obvious typo
moreover, @gpaulos , https://github.com/RackHD/RackHD/pull/560 is a workaround, please do fix the ultimate root cause.
> fix the obvious error message problem..

- test/stream-monitor/flogging/infra_logging.py
- test/stream-monitor/stream_sources/log_type.py
* This commit  also includes changes for RAC-3776
* Place process, path, and greenlet informaton at end of trace line as suffix
* If 1st character of message is ' +-', don't include suffix information
* Give each test a indentification number
* Remove addtional lines for test block start, test start and test end messages
* Created new simple format and rename origial format to 'original'
* Start block and test ID at 1 instead of 0
> RAC-3778 - re-factor log formtting

- debian/changelog
Prepare to Release
* change debian/package version and contacts.
> [skip ci]modify package info for release

- packer/ansible/rackhd_release.yml
- packer/ansible/roles/rackhd-builds/tasks/main.yml
http://rackhdci.lss.emc.com/job/BuildRelease/job/Build/job/ova-build/131/console failed due to this reason.
> [Skip CI]Fix Typo is_relaese

- test/tests/api/v2_0/sel_alert_poller_tests.py
modify AMQP message format in api 2.0 sel alert tests to align with the new event format design.
@sunnyqianzhang @nortonluo @anhou @pengz1 
jenkins: depend on https://github.com/RackHD/on-tasks/pull/380
> modify CIT api2.0 sel tests to align with the new event format

- test/requirements.txt
@stuart-stanley @hohene @johren
> rac-4040 Pin nose-dep to required version:

- test/deploy/rackhd_package_install.py
Fixed package installer for new FIT configuration system.
NOTES:
lines 18-19: removed reference to deprecated -ora arguments
line 82: revision to accommodate docker deployments
lines 157-215: using generated 'config.json' from FIT config.
@hohene @jimturnquist @johren @larry-dean
> Updated deploy/rackhd_package_install.py for new configuration system

- test/benchmark.py
- test/common/api_utils.py
- test/common/fit_common.py
- test/common/test_api_utils.py
- test/config/settings.py
- test/mkcheck.sh
- test/modules/amqp.py
- test/pylintrc
- test/stream-monitor/sm_plugin/__init__.py
- test/tests/api/v1_1/discovery_tests.py
- test/tests/api/v1_1/lookups_tests.py
- test/tests/api/v1_1/profiles_tests.py
- test/tests/api/v1_1/workflows_tests.py
- test/tests/api/v2_0/lookups_tests.py
- test/tests/api/v2_0/workflows_tests.py
- added mkcheck.sh script to perform pylint checking (and
anything else we may eventually want to check).  This
can be used by Jenkins as a code quality gate.
- Usage: ./mkcheck <html|text>
- pylint output is stored in rackhd_test_pylint.text or rackhd_test_pylint.html
depending on which pkg_format is requested.  default is text.
- Only actual errors are checked for ("pylint -E").  Cleaning
up warnings is for another day.
- Updated a handful of errors that existed presently in RackHD/test
- update pylintrc to match more modern pylint
> RAC-4005  Pylint cleanup in RackHD/test

- test/tests/api/redfish_1_0/event_service_tests.py
needed for:
https://github.com/RackHD/on-http/pull/579
> Add required fields to payload

- test/common/api_utils.py
- test/common/test/api_utils_test.py
* Changed all prints to LOG
* Use fitargs instead of system environment
* Added exception handling of API() calls
* Variable names are now consistent
* api_node_select_argList() to api_node_select_from_config()
> RAC-4064 - common/api_utils need to use LOG and new config

- test/util/apply_obm_settings.py
New utility to set OBMs on all or selected nodes using fit_common.apply_obm_settings() routine.
@hohene @jimturnquist @larry-dean @stuart-stanley @johren
> Initial commit util/apply_obm_settings.py

- docker/docker-compose.yml
- docker/scripts/compose_services.bash
config file of kibana docker image file has been moved from ```/opt/kibana/config/kibana.yml``` to ```/etc/kibana/kibana.yml```
reference: https://hub.docker.com/_/kibana/
> [skip ci]config in kibana docker image has been moved location

- example/samples/install_coreos_payload_full.json
- example/samples/install_coreos_payload_minimum.json
> align coreos repo address with other OS

- docker/docker-compose-centos.yml
- docker/docker-compose-mini.yml
The mini and centos yml missing ${TAG}
> [skip ci]add  in mini and centos yml

- test/config/install_default.json
- test/requirements.txt
- test/tests/amqp/test_amqp_racknode.py
Add AMQP test for racknode operation. This test validate the new AMQP message format in the unified event notification system(RI-45). This PR also add AMQP test ability to FIT.
> Add AMQP test for Racknode operation in new event notifaction format 

- test/deploy/rackhd_ha_install.py
Configure cluster properties with stonith, quorum and migration-threshold
> RAC-4451 Add test to set cluster properties in HA cluster

- test/tests/api/v2_0/skupack_tests.py
After posting the sku, the RackHD will run sku discovery workflow and assign the node with new sku. Previously the test case hard-codes to wait only 3 sec. But we found this delay is not enough in some system, and the Jenkins continuous smoke test occasionally reports this test case failure.
This some of the failure jobs: 
- http://rackhdci.lss.emc.com/job/Templates/job/SmokeTest-CIT/1321/ 
- http://rackhdci.lss.emc.com/job/Templates/job/SmokeTest-CIT/1508/
Below is the log that captured from jenkins, you could see it took more than 4 sec to finish the new sku discovery.
- The time when RackHD receives the request to create sku.
```
1|on-http  | [debug] [2017-03-03T06:06:29.120Z] [on-http] [Http.Server] [Server] http: POST 201 927.742 - f1a5fdcf-fbb7-4aa0-a398-d9ac8dfabc1c - /api/2.0/skus …
```
> add retries for get_sku_nodes test case

- packer/ansible/roles/pm2/files/rackhd-pm2-config.yml
- test/common/fit_common.py
- test/config/stack_config.json
- test/tests/ucs/test_rackhd_api_ucs.py
- test/tests/ucs/test_ucs_api.py
Note: This PR will fail because the CI infrastructure doesn’t include the virtual ucs VMs.
@keedya  is working on. However, this work has been tested in sandbox and it passes.
Please go ahead and review the PR despite of the failure.
The tests in this file tests:
-The APIs that are provided by the ucs-service:
https://github.com/RackHD/ucs-service 
-The ucs discovery workflow
-ucs catalog workflow
@hohene @gpaulos @stuart-stanley @RackHD/veyron
> Add functional test for the UCS service.

- test/tests/api/v2_0/obm_tests.py
- test/tests/api/v2_0/os_install_tests.py
@RackHD/corecommitters  @hohene @srinia6
> Fix 2.0 os install

- test/tests/amqp/test_amqp_heartbeat.py
Adding test to monitor AMQP heartbeat message.
> Add test for heartbeat AMQP message

- test/tests/ucs/test_rackhd_api_ucs.py
- test/tests/ucs/test_ucs_api.py
jenkins: depends on https://github.com/RackHD/ucs-service/pull/14
> change ucs tests to use https

- test/deploy/rackhd_source_install.py
rackhd_source_install.py now invokes install_swagger-ui.sh
and install-web-ui.sh.
@gpaulos @hohene @stuart-stanley
> RAC-4567 update rackhd_source_install with swagger-ui and web-ui

- test/common/fit_common.py
This PR fixes some technical debt in fit_common.py:
•removed obsolete function appliance_reset() which used BMC to reset the appliance in the old MN lab. No longer relevant, because it doesn't work with Vagrant or with ESXi stacks. Can just use remote_shell('reboot') for a reset.
•removed obsolete function apply_obm_settings_seq(), apply_obm_settings() is the current supported version
•fixed mongo_reset() which was set up for OnRack configuration and broken for current, Now works with RackHD source and package installations.
@hohene @larry-dean @jimturnquist @stuart-stanley @johren
> Commit fit_common.py

- test/tests/api/v2_0/os_install_tests.py
- test/tests/api/v2_0/workflows_tests.py
@yyscamper I closed the other unintentionally .
Here is the response to your comments:
- Env variables are not shared between executors in jenkins
- I added sorting in the code to make sure I have consistency in node's order
- pipeline is not part of my task. Although i have a job running in sandbox using my branch to run all OSs in parallel
- I can send you a link to the  sandbox job offline
Adding @RackHD/corecommitters @geoff-reid @brianparry @hohene
> Add run os install on node per index

- test/tests/ha/rackdh_ha_resource_test.py
* Pacemakerr status and configuration
* Mongo status and configuration
* Rabbit status and configuration
* RackHD components
> RAC-4534 - Validate the general configuration of the installed components

- test/tests/ucs/test_rackhd_api_ucs.py
Fix for https://rackhd.atlassian.net/browse/RAC-4559
The fit_comon.rackhdapi() routine uses an empty array as the default payload.  The 2.0/nodes/id/workflows API requires an object as a payload instead of an array.  The fix is to pass an empty object to the routine.  
@keedya @uppalk1 @tannoa2 @RackHD/corecommitters 
removing "depends on" since the fix has been merged into on-tasks
> fix ucs catalog test and enable for smoke test

- test/config_templates/rabbitmq_policy.bash
- test/deploy/rackhd_ha_resource_install.py
Add test for rabbitmq 
Configure rabbitmq resource and virtual IPs
Co-locate resource with virtual IPs
Anti-colocation between two resource
Create mirrored queue policy for rabbitmq cluster
> RAC-4250 Deploy rabbitmq as pacemaker resource

- test/tests/ucs/test_ucs_api.py
@tannoa2 @keedya @uppalk1 @RackHD/corecommitters
> add UCS power control functional tests

- packer/ansible/roles/remoterepos/tasks/main.yml
@RackHD/veyron @michaelsteven
removing 1.1 apidoc generation from ansible script
> removing 1.1 api doc generation in ansible script

- test/config/stack_config.json
- test/tests/ucs/test_ucs_api.py
@keedya @tannoa2 @RackHD/corecommitters
> force all FIT UCS tests to skip until UCSPE issue is resolved

- example/README.md
@DavidjohnBlodgett @panpan0000 @anhou : Updates to the README only for the vagrant set up.
> Update to the README

- test/stream-monitor/stream_sources/amqp_source.py
Problem is actually misconfiguration. However, the ssh-helper should not kill the whole test suite, but should instead should only disable AMQP based Stream Monitors
This change:
* explicitly calls out the EOF exception and logs a warning indicating that this is likely a misconfiguration
* broadens the existing exception catch to prevent -any- failure from stopping the entire suite (it should only disable this particular stream-monitor)
@johren @hohene
> RAC-4957 FIT ssh failure in OVA Post Test

- test/tests/rackhd20/test_rackhd20_api_notifications.py
> Turning off the notification test for now until we fix RAC-4965

- packer/template-ubuntu-14.04.json
- packer/template-ubuntu-16.04.json
@king-jam @brianparry @amymullins @geoff-reid @johren
> Make OVA memory size 4GB for ubuntu 14 and 16

- test/tests/api/fit-staging/v2_0/catalogs_tests.py
- test/tests/api/fit-staging/v2_0/config_tests.py
- test/tests/api/fit-staging/v2_0/lookups_tests.py
- test/tests/api/fit-staging/v2_0/nodes_tests.py
- test/tests/api/fit-staging/v2_0/obm_settings.py
- test/tests/api/fit-staging/v2_0/obm_tests.py
- test/tests/api/fit-staging/v2_0/os_install_tests.py
- test/tests/api/fit-staging/v2_0/pollers_tests.py
- test/tests/api/fit-staging/v2_0/schema_tests.py
- test/tests/api/fit-staging/v2_0/sel_alert_poller_tests.py
- test/tests/api/fit-staging/v2_0/skupack_tests.py
- test/tests/api/fit-staging/v2_0/swagger_tests.py
- test/tests/api/fit-staging/v2_0/tags_tests.py
- test/tests/api/fit-staging/v2_0/users_tests.py
- test/tests/api/fit-staging/v2_0/workflowTasks_tests.py
- test/tests/api/fit-staging/v2_0/workflows_tests.py
This PR is for staging the CIT api/v2_0 test scripts into a temp directory for follow on PRs.
This will allow for doing diffs between original and converted scripts, without losing the master.
The scripts in this PR are a copy of the scripts in /test/tests/api/v2_0 only, NO updates,
They won't run as part of the CIT or FIT smoke tests in this form.
Plan is:
1. copy the original scripts into this staging area (this PR)
2. mv the staged script and apply the converted script on top do show the diffs only for review
3. allow the converted script to run in FIT smoke suite.
For this PR, please ignore the hound errors. This PR is copying existing scripts into a staging directory, and the hound errors will be fixed when we apply the NEW converted scripts.
> Rac 4181 - FIT api/v2_0 staging of CIT scripts being converted.

- test/tests/api/v2_0/nodes_tests.py
PR to fix functional test @RackHD/corecommitters 
Jenkins: depends on https://github.com/RackHD/on-http/pull/639
> Functional test fix for PR-639

- test/tests/api/fit-staging/v2_0/skupack_node_updates.py
- test/tests/api/fit-staging/v2_0/skupack_tests.py
* 	Reworked skupack_tests.py to better handle post/put/patch.
* 	Created skupack_node_updates.py to test sku attachement and de-attachment
* 	flake8 corrections
> RAC-5031 - Conversion and testing of CIT Skupack tests

- test/tests/api/fit-staging/v2_0/workflowTasks_tests.py
- test/tests/api/fit-staging/v2_0/workflows_tests.py
Converted the workflows CIT test scripts to FIT format.
This is first part of committing these changed scripts to show the diffs.
> RAC-5032 - Converted the workflows CIT test scripts to FIT format for staging

- test/common/fit_common.py
Added new argument -nodeindex to fit_common.py as an additional modifier to the node_select() method. 
This was requested as a tool to select target nodes for Jenkins OS installations when nodeid or MAC address is undefined.
@larry-dean @johren @hohene
> Added -nodeindex parameter to fit_common.py

- test/tests/api/fit-staging/v2_0/schema_tests.py
- test/tests/api/fit-staging/v2_0/swagger_tests.py
- test/tests/api/fit-staging/v2_0/tags_tests.py
Converted the workflows CIT test scripts to FIT format.
This is first part of committing these changed scripts to show the diffs.
tags, schema, swagger CIT test scripts.
> RAC-5104 -  Converted CIT formatted apiv2 scripts to FIT format -tags, schema, swagger scripts 

- test/tests/api/fit-staging/v2_0/catalogs_tests.py
- test/tests/api/fit-staging/v2_0/config_tests.py
- test/tests/api/fit-staging/v2_0/lookups_tests.py
- test/tests/api/fit-staging/v2_0/pollers_tests.py
Converted the workflows CIT test scripts to FIT format.
This is first part of committing these changed scripts to show the diffs.
catalogs, configs, lookups, pollers
> RAC-5103 - Converted misc CIT formatted apiv2 scripts to FIT format - catalogs, etc.

- .gitmodules
- docker/docker-compose-dev.yml
- docker/docker-compose-mini-dev.yml
- docker/docker-compose-mini.yml
- docker/docker-compose.yml
@RackHD/corecommitters @RackHD/veyron
> Add ucs-service to docker-compose files

- debian/control
Fix for [RAC-5270](https://rackhd.atlassian.net/browse/RAC-5270) 
@RackHD/corecommitters @RackHD/veyron
> add ucs-service to debian build

- test/config/install_centos65_minimum.json
- test/tests/bootstrap/test_api20_linux_bootstrap.py
This is the PR gate CenntOS 6.5 FIT OS install test.
This PR is a prerequisite to the main PR from on-build-config.
This PR only includes a payload file and an increase in the OS install timeout.
@johren @hohene
> RAC-5040 CentOS 6.5 FIT OS Install

- test/tests/rackhd20/test_rackhd20_api_decommission_node.py
* Created fit version of decommission test
> RAC-4819 - convert decommission nodes script to FIT

- test/common/fit_common.py
- test/tests/redfish10/test_redfish10_api_systems.py
- Support Dell/Non-Dell in these tests
This will depend on https://github.com/RackHD/on-http/pull/663 for success.
> RAC-4172 Update fit testing for Ethernet & BIOS.

- packer/ansible/roles/monorail/files/config.json
Signed-off-by: Azzam Tannous <azzam.tannous@emc.com>
> Added a yaml File Name property to the config file

- packer/ansible/roles/monorail/files/config.json
Reverts RackHD/RackHD#777 due to https://rackhd.atlassian.net/browse/RAC-5337
> Revert "Added a yaml File Name property to the config file"

- test/config/install_centos70_minimum.json
- test/config/install_coreos_minimum.json
- test/config/install_esxi5.5_minimum.json
- test/config/install_opensuse42.1_minimum.json
Additional tested Minimum payload files for all OS's except Windows.
Paired with Derrick
@johren @derrickostertag
> RAC-5064-5065-5066-5067-5068_OS minimum payloads

- test/tests/ucs/test_rackhd_api_ucs.py
Jenkins: depends on https://github.com/RackHD/on-tasks/pull/457, https://github.com/RackHD/ucs-service/pull/22, https://github.com/RackHD/on-http/pull/666
@RackHD/veyron @RackHD/corecommitters
> add redfish/v1/chassis tests to UCS

- test/tests/api-cit/v2_0/sel_alert_poller_tests.py
* Added logic skip test of AMQP server not active
> rac-5400 - Failed at case SELPollerAlertTests

- test/tests/api-cit/v2_0/nodes_tests.py
> RAC-5393 - CIT to FIT update the converted scripts to remove references to prior AMQP process

- docker/dell/config/gateway.yml
Zuul filter for discovery range split changes.
> Zuul filter for discovery range split changes.

- docker/dell/set_config.sh
- docker/dell/set_rackhd_smi_config.sh
Un-commenting a line that should not have been comented.
Adding a file to make it easier to invoke the taskgraph that updates the smiConfig.json
> Fix for dell microservice configuration

- test/deploy/rackhd_stack_init.py
- test/util/display_rackhd_nodes.py
Add displaying of nodes from rackhd_stack_init.py
Updated the standalone util display_rackhd_nodes.py
> RAC-5419 node inventory

- test/config/install_centos65_minimum.json
- test/config/install_centos70_minimum.json
- test/config/install_coreos_minimum.json
- test/config/install_esxi5.5_minimum.json
- test/config/install_esxi6.0_minimum.json
- test/config/install_opensuse42.1_minimum.json
- test/config/install_ubuntu14.04_minimum.json
* added 2 hour (7200000 ms) timeout to workflow options
* beautified json
> RAC-5425 - FIT ESXi Install high failure rate

- test/common/fit_common.py
- test/common/test_api_utils.py
- test/tests/compute/test_api20_node_delayed_rediscovery.py
- test/tests/compute/test_api20_node_immediate_rediscovery.py
- Add a single function to get IPMI user from node catalog
- Added the test to preload unidentified compute sku
> rac-5340 Implement the immediate and  delayed rediscovery test for FIT

- test/config/install_centos65_maximum_QuantaT41.json
Maximum payload file for CentOS 6.5 OS install in regression testing for Quanta T41.
Paired with @gpaulos
> RAC-5604 Centos 6.5 maximum payload for regression test

- test/classes/administrator.py
- test/classes/operator.py
- test/classes/readonly.py
- test/classes/user.py
- test/dellemc-test
- test/requirements.txt
- test/tests/security/test_api_security_login.py
RAC-223: security login test
* updated security login tests from OnRack/Autotest to test against RackHD
* tests login with current RackHD roles, User, Administrator, and Operator
> RAC-223: security login test

- test/config/install_centos70_maximum_QuantaT41.json
Created "install_centos70_maximum_QuantaT41.json" for regression test
> RAC-5605 Centos_7_maximum_payload

- test/deploy/rackhd_microservice_install.py
This script is used for deploying micro-services through FIT.
@derrickostertag @jimturnquist @hohene @manfrednde
> RAC-5527 : FIT implementation of microservices install

- test/config/install_opensuse42.1_maximum_QuantaT41.json
> RAC-5608 OpenSuse maximum payload OS install

- test/config/install_rhel70_maximum_QuantaT41.json
RAC-5636 RHEL 7 maximum payload OS install file
Paired with Larry Dean.
> RAC-5636 RHEL 7 maximum payload OS install file

- test/config/install_esxi6.0_maximum_QuantaT41.json
> RAC-5610 ESXi 6.0 maximum payload OS install

- test/tests/redfish10/test_redfish10_api_managers.py
Jenkins: depends on https://github.com/RackHD/on-http/pull/696
> Add fun tests for SerialInterfaces

- test/config/install_esxi5.5_maximum_QuantaT41.json
Basically the same as the ESXi 6.0 max payload.
> RAC-5609 ESXi 5.5 maximum OS Install Payload

- test/config/install_coreos_maximum_QuantaT41.json
> RAC-5606 CoreOS maximum OS install payload

- test/config/install_centos70_maximum_QuantaT41.json
- test/config/install_coreos_maximum_QuantaT41.json
- test/config/install_esxi5.5_maximum_QuantaT41.json
- test/config/install_esxi6.0_maximum_QuantaT41.json
This PR changes some of the OS install max payload files to match the Hopkinton baremetal stack configuration.
> RAC-5665 Fix max payloads for Hopkinton baremetal stack

- test/tests/redfish10/test_redfish10_api_taskservice.py
* This change is compatible the current TaskCollection
> RAC-5752 - Correct tests to support TaskCollection compliance changes

- test/tests/bootstrap/pr_gate_os_install.py
Parallel OS install script for optimized PR gate. 
Paired with Erika
@jimturnquist @hohene
> RAC-5422 pr gate os install

- test/runFIT.sh
Add script to run FIT.
The steps of the script:
1. set up config for FIT
2. create virtual environment 
3. run test and collect test report under workspace/xunit-reports
The PR is the first step of job : refactor pipeline scripts.
@panpan0000 @changev @anhou @iceiilin
> add script to run FIT

- test/requirements.txt
This PR removed unused Python modules from FIT requirements.txt.
@hohene @jimturnquist
> RAC-5829 Cleanup FIT requirements.txt

- test/deploy/rackhd_redfish_service_validator.sh
This is a shell script to run the Redfish Service Validator
@hohene @jimturnquist
> RAC-5818 Redfish Validator helper script deploy/rackhd_redfish_service_validator.sh

- test/tests/api-cit/redfish_1_0/systems_tests.py
- test/tests/redfish10/test_redfish10_api_systems.py
Update test case to use common format for LogServices/SEL vs sel.
Paired with Derrick.
@derrickostertag @jimturnquist
> RAC-5683 - Update api-cit test script to ignore case sensitivity for SEL vs sel.

- packer/ansible/roles/monorail/files/config.json
> update config.json for taskgraph changes

- docker/monorail/config.json
- packer/ansible/roles/monorail/files/config.json
- test/config/rackhd_default.json
- test/tests/bootstrap/pr_gate_os_install.py
- test/tests/bootstrap/test_api20_os_bootstrap_parallel_local.py
- test/tests/bootstrap/test_api20_os_bootstrap_parallel_proxy.py
- test/tests/bootstrap/test_redfish10_os_bootstrap_base.py
- test/tests/bootstrap/test_redfish10_os_bootstrap_parallel.py
jenkins: depends on https://github.com/RackHD/on-build-config/pull/305
@RackHD/committers
> Use SB route for statci file server, and port 9030 for taskgraph

- test/tests/redfish10/test_redfish10_api_systems.py
This fixes a failure when running FIT on an infrasim virtual Dell r630.  
@RackHD/committers
> fix for empty Created field in SEL records

- test/tests/api-cit/redfish_1_0/task_service_tests.py
CIT test fix for RAC-5913, required for PR 750
Paired with Derrick
@derrickostertag @jimturnquist
> RAC-5913 fix CIT test 

- test/tests/redfish10/test_redfish10_api_systems.py
FIT test fix for this PR:
https://github.com/RackHD/on-http/pull/752
Merge this first.
@derrickostertag @jimturnquist
> RAC-6023 FIT test fix

- test/deploy/rackhd_redfish_service_validator.sh
Revised the rackhd_redfish_service_validator.sh script to reflect changes in the master repo. Added some additional checks and saved the commit ID in the directory name.
Paired with Derrick
@jimturnquist @derrickostertag
> RAC-6025 Revised rackhd_redfish_service_validator.sh for changes in repo

- packer/build_box.sh
- packer/cleanup_vbox.sh
Implement a shell script to build vagrant box.
Test:
http://10.**.**.17*:8080/job/pengtian/job/BuildVagrantBox/
@panpan0000 @changev @anhou @iceiilin
> RAC-5938 :Refactor vagrant build shell script

- packer/ansible/roles/rackhd-builds/tasks/main.yml
- packer/template-ubuntu-14.04.json
- packer/template-ubuntu-16.04.json
@PengTian0 
@iceiilin 
test log:
http://10.62.**.1**:8080/job/pengtian/job/vagrant/job/build/13
> fix the deb_repository passing from packer to ansible

- test/tests/redfish10/test_redfish10_api_managers.py
Paired with @pathakvaidehi2391 @jimturnquist
> RAC-5911 Added 404 response for rackhd manager serial interface

- packer/ansible/roles/setuptools/tasks/main.yml
- packer/build_ova.sh
extract build_ova.sh from HWIO-BUILD
@panpan0000 @PengTian0 
waiting for https://github.com/RackHD/RackHD/pull/875 to be merged
> RAC-5940 Refactor/build ova sh

- test/runFIT.sh
Sync the PR: https://github.com/RackHD/on-build-config/pull/306: Add a check for nodes to be discovered before starting stack init
@panpan0000 @changev @HQebupt @iceiilin @anhou 
Test job: http://rackhdci.lss.emc.com/job/Archiving/job/tian/job/pr/job/prgate/
> Add waitting for nodes to runFIT.sh

- test/tests/redfish10/test_redfish10_api_systems.py
FIT test fix for RAC-6045. Prerequisite for on-http PR: https://github.com/RackHD/on-http/pull/761
Paired with @derrickostertag 
@jimturnquist
> RAC-6045 fix FIT test

- packer/build_ova.sh
support ova cache build refactor
@PengTian0 @panpan0000
> RAC-6078 refactor build ova for build template

- packer/box_handler.sh
- packer/build_vagrant_base_box.sh
> RAC-6079 bugfix: build ovf throw error when targetdir=pwd

- packer/ansible/roles/images/tasks/main.yml
- packer/ansible/roles/mongodb/tasks/main.yml
Update config file due to RackHD install from source code in ubuntu 16.04.
- Related PR: [/docs/pull/405](https://github.com/RackHD/docs/pull/405/files)
@changev @PengTian0 @panpan0000
> [RAC-6136] update config file due to RackHD install in ubuntu 16.04

- docker/docker-compose.yml
@geoff-reid  @tannoa2 @dalebremner @tgelter
> fix docker-compose to build dependencies with the right tag

- test/tests/amqp/test_amqp_node_rediscover.py
- test/tests/api-cit/redfish_1_0/systems_tests.py
- test/tests/imageserver/test_image_service_system.py
- test/tests/redfish10/test_redfish10_api_systems.py
- test/tests/redfish10/test_redfish10_system_reset_base.py
depends on: https://github.com/RackHD/on-http/pull/809
> Changed reset_type to ResetType to match Redfish standard

- docker/default.yml
- docker/setup-network.sh
- docker/start-node.sh
@keedya @tannoa2 @dalebremner @uppalk1
> added scripts for docker development environment

- test/tests/ucs/test_rackhd20_ucs_pollers.py
Add retry to get ucs poller data
@anhou @pengz1
> RAC-6415: Add retry to testing ucs poller data

- test/tests/ucs/test_rackhd20_ucs_pollers.py
- test/tests/ucs/test_rackhd20_ucs_redfish_api.py
> Add retry to testing ucs poller data cache

- test/tests/ucs/test_rackhd20_ucs_discovery.py
Update UCS re-discovery node counting methods.
@PengTian0 @anhou @bbcyyb
>  Fix UCS discovery bug

- example/samples/install_debian_payload_full.json
- example/samples/install_debian_payload_minimal.json
- example/samples/install_ubuntu_payload_full.json
- example/samples/install_ubuntu_payload_minimal.json
Depends on : [docs/421](https://github.com/RackHD/docs/pull/421)
Debian full and minimum sample files added and ubuntu edited to work with new installation graph
> Adding debian sample files

- example/samples/install_rhel_payload_full.json
- Added sample for bonded interface, enable and disable services
- List of additional packages and envionments that can be added to the post-installation
> RHEL Support

- test/tests/api-cit/v2_0/nodes_tests.py
depends on: https://github.com/RackHD/on-http/pull/830
@RackHD/corecommitters @pengz1
> return 404 when tagname is not found

- docker/dell/config/gateway.yml
- docker/monorail/smiConfig.json
- example/rackhd/monorail/smiConfig.json
- packer/ansible/roles/monorail/files/smiConfig.json
* add powerThermalMonitoring service and powerthermal/create/detach endpoints in gateway.yml
* add credentials of obm and shareFolder in smiConfig.json
https://rackhd.atlassian.net/browse/RAC-6544
@RackHD/corecommitters @iceiilin @nortonluo
> update smiConfig.json and gateway.yml

- README.md
- example/infrasim/docker-compose.yml
- example/infrasim/start_infrasim.sh
- example/infrasim/vnc_forward.sh
- example/rackhd/docker-compose.yml
- example/rackhd/monorail/static/http/index.html
**AC**:
1. Added ```sleep 1``` in start_infrasim.sh to make sure infrasim get ip address after service started.
2. Refined ```rackhd/monorail/static/http/index.html``` , deleted some useless links, resolve ip address from user input url instead of ```localhost```.
3. Modified ```rackhd/docker-compose.yml``` to expose Rabbitmq's port.
4. Added vnc_forward script
@iceiilin @pengz1 @leoyjchang @anhou
> Fix some bugs for vLab environment
