example/dev.yml, example/roles/repos/tasks/main.yml
NOTE: names of these files vary around a bit, we may need to massage the
default workflows to match the relevant filenames for the demo setup
Total "vagrant up" time with bintray downloads enable = 20 min (from my coffee shop & laptop)
=> adding file replication from builds into bintray

.gitignore, .gitmodules, example/README.md, example/Vagrantfile, example/bin/monorail_rack, example/roles/node/tasks/main.yml, example/roles/repos/tasks/main.yml, example/samples/virtualbox_install_coreos.json, example/samples/virtualbox_sku.json
Adding ansible tasks to pull down and install CoreOS installation
media (since it's small) to provide an example OS installation flow
with RackHD. Maps to the location and flow from the install-coreos.ipxe
profile (in on-http) and the "Task.Os.Install.CoreOS" workflow task in
on-tasks.
=> adding coreos install media

example/README.md, example/roles/build/tasks/main.yml, example/roles/repos/tasks/main.yml, scripts/reset_submodules.bash
functional, but partial fix to demo setup. Updated instructions rely on
https://github.com/RackHD/on-http/pull/56 and
https://github.com/RackHD/on-http/pull/57, and the on-http submodule to
be updated to include both of those commits.
- resets the default SSH key for remote access (note: CoreOS SSH login not
working per these instructions - not sure what I'm missing and haven't
debugged login yet)
- adding instructions and quick-links to download and unpack ESXi and
CentOS7 iso images, and link them into the vagrant install
- in support of the annotations in
https://github.com/RackHD/docs/pull/203 to point readers to this
local README for quick-setup instructions
- adds a script to make it easier to update the submodules to 'master' for 
demo work
=> partial fix to demo setup

example/dev.yml, example/roles/apt/tasks/main.yml, example/roles/build/tasks/main.yml, example/roles/git/tasks/main.yml, example/roles/ipmitool/tasks/main.yml, example/roles/isc-dhcp-server/tasks/main.yml, example/roles/mongodb/tasks/main.yml, example/roles/rabbitmq/tasks/main.yml, example/roles/snmptool/tasks/main.yml
It was suggested to only run apt-get update on the first role we run to elevate repetitive actions. I have made the fix. @heckj @benbp
=> removed all but one apt-get update from roles

test/tests/nodes_tests.py, test/tests/obm_tests.py
- Delete redundant test_node_id_obm_create()
- Move OBM identify test into OBMTests() and set check-obm dependency
@RackHD/corecommitters @zyoung51 @tannoa2 @keedya @uppalk1
=> Fix OBM tests

packer/ansible/roles/foreman/files/Procfile
Per slack conversation on 1/8 #RackHD, debugging Pasu's issues
really needed to see the logs - and what was missing from them,
so I thought it might be beneficial to capture them in the procfile
setup on a per-run basis, hence this update.
=> ammending procfile to capture logs

packer/ansible/roles/images/tasks/main.yml
undionly.kpxe from ipxe is not the original gPXE's undionly.kkpxe from syslinux  which has been validated for installing ESXi on multiple platforms, correct it here. This will fix the chainload failure issue when installing ESXi OS
related PR: 
https://github.com/RackHD/on-imagebuilder/pull/17
https://github.com/RackHD/on-http/pull/91
=> Fix ESXi installation chainloader from ipxe to syslinux

test/config/settings.py, test/tests/amqp_tests.py, test/tests/nodes_tests.py
- Apply compute node count, check against graph status count
- Remove static node count
- Get status from AMQP message body (avoid persistent status)
@RackHD/corecommitters @tannoa2 @uppalk1 @zyoung51 @keedya
=> Node discovery updates

example/README.md
The links for the previous ISO is no longer working. Changed to a link using the MIT mirror which will hopefully prove to be more stable long-term
Signed-off-by: Kendrick Coleman <kendrickcoleman@gmail.com>
=> updated link for CentOS ISO download

test/tests/api/v1_1/nodes_tests.py, test/tests/api/v1_1/workflowTasks_tests.py, test/tests/api/v1_1/workflows_tests.py
See https://github.com/RackHD/on-http/pull/145 for more information. Requires https://github.com/RackHD/on-http/pull/145/files as well.
A lot of these tests have been returning false positives because the on-http server was incorrectly returning 200 status codes when it should have been returning 400 and 404 status codes. Recent updates to on-http now return proper error status codes, which is now breaking these tests.
@RackHD/corecommitters @VulpesArtificem @heckj
=> Fix workflow related API tests

packer/ansible/roles/images/tasks/main.yml
- updating microkernel versions to 3.16.0-25 to match on-http code
updates
- adding undionly.kkpxe bootloader pull from syslinux
Attempted to do the vagrant demo run-through with a fresh built VM from master, and the Ansible roles in packer still had references to the older kernel files for setting this up.
Also looks like we never included in the syslinux undionly.kkpxe bootloader in there
=> updating microkernel and bootloader for ESX

test/config/api1_1_config.py, test/requirements.txt, test/tests/api/v1_1/amqp_tests.py, test/tests/api/v1_1/config_tests.py, test/tests/api/v1_1/lookups_tests.py, test/tests/api/v1_1/nodes_tests.py, test/tests/api/v1_1/obm_settings.py, test/tests/api/v1_1/obm_tests.py, test/tests/api/v1_1/profiles_tests.py, test/tests/api/v1_1/workflowTasks_tests.py, test/tests/api/v1_1/workflows_tests.py
This uses the latest api1.1 client library ```pip install on_http_api1_1``` generated off monorail.yml (with auth settings).   Keeps library imports consistent with redfish 1.0 and 2.0 api's. 
@RackHD/corecommitters @zyoung51 @WangWinson @uppalk1 @keedya @geoff-reid @brianparry
=> Update 1.1 API tests to use latest python client library

test/tests/api/v1_1/lookups_tests.py
This is a bad request, not an internal server error. Now that we properly handle the error, return the right response code.
Requires https://github.com/RackHD/on-core/pull/99, passing locally.
@RackHD/corecommitters @zyoung51 @tldavies
=> Assert 400 error on duplicate lookup entry creation

example/README.md
Just found that env variable will not work with lower case. This may confuse user
=> Should use upper case for PXE_COUNT

test/tests/api/v2_0/pollers_tests.py
* Fix issue caused by poller run during test.
* Check only a subset of keys in returned data.
This PR fixes an issue where pollers_get_by_id test fails if pollers run during the test.
=> 2.0 API pollers test bug fix.

packer/ansible/roles/isc-dhcp-server/files/dhcpd.conf.noproxy
Example to allow DHCP server to send bootfile request with mac/ip query.
Static host entry example
Handle option 93 arch type check
@RackHD/corecommitters @geoff-reid @keedya @zyoung51 @uppalk1 @tannoa2
=> Add dhcpd.conf example to request profile without proxy.

docker/README.md, docker/create_pxe_vm.bash, docker/docker_vm_up.bash, docker/monorail/config.json, docker/scripts/compose_services.bash, docker/scripts/follow_services.bash, docker/scripts/remove_services.bash, docker/scripts/restart_services.bash, docker/scripts/stop_services.bash
* Adds scripts that can be used as an alternative to `docker-compose`
* Adds `create_pxe_vm.bash`
* Update README to help troubleshoot common issues, and document new scripts.
=> Adds alternative scripts to docker-compose, and update README

packer/ansible/roles/monorail/files/config.json
- partial resolution for https://github.com/RackHD/RackHD/issues/146
- to work with https://github.com/RackHD/on-http/pull/187
=> remove 'current' from proxy config in CoreOS demo proxy setup

test/requirements.txt, test/tests/api/v2_0/catalogs_tests.py, test/tests/api/v2_0/config_tests.py
Fixed the catalogs and config tests to work with the new api 2.0 library version 1.0.2.  This is a required fix before PR#160 can be merged.
=> Fix functional tests to work with new api 2.0 library version 1.0.2

example/Vagrantfile
This speeds up testing/running of our services by a lot.
OSX has nfsd installed by default, not sure about linux.
@jlongever @heckj @DavidjohnBlodgett @rolandpoulter @RackHD/corecommitters
=> Add example configuration for NFS shared folders

test/tests/api/v1_1/workflowTasks_tests.py
Fix for issue 170: https://github.com/RackHD/RackHD/issues/170  
Change putWorkflowTasks test to no be dependent on the
position of the new workflow task in the results.
@abildw @srinia6 @dalebremner @RackHD/corecommitters
=> Fix for RackHD issues #170, failing PUT:/workflowTasks test

docker/Vagrantfile, docker/docker-compose.yml, docker/elasticsearch/config/elasticsearch.yml, docker/elasticsearch/config/logging.yml, docker/monorail/config.json, docker/reload_docker_vm.bash
These changes configure Elasticsearch to enable CORS headers for "*" domains. This allows the UI to make API calls to Elasticsearch.
=> Fix elasticsearch CORS settings and docker Vagrantfile

test/tests/api/v2_0/workflows_tests.py
Fix dependencies in the 2.0 workflows tests.  Also change the mock data values so the 1.1 tests do not affect the 2.0 tests.  
This change will allow the 2.0 workflow tests to be successfully run independent of the 1.1 workflow tests.
=> fix workflows 2.0 test dependencies

docker/README.md
`docker-compose start` cannot work after `docker-compose pull`, need `docker-compose up` to create firstly ,and also need `sudo` privilege 
@RackHD/rackhd_dev @RackHD/corecommitters @rolandpoulter
=> Update readme for Linux host

test/tests/api/v1_1/nodes_tests.py, test/tests/api/v2_0/nodes_tests.py
Discovery waits for task completion and fails test on a timeout to avoid waiting forever. 
@RackHD/corecommitters @uppalk1 @zyoung51 @tannoa2 @geoff-reid @keedya
=> Run discovery handler in worker thread

test/tests/api/redfish_1_0/__init__.py, test/tests/api/redfish_1_0/account_service_tests.py
- retrieve the account service root
- retrieve the list of roles at /AccountService/Roles
- retrieve role informaiton at /AccountService/Roles/{name}
- retrieve the list of accounts at /AccountService/Accounts
- retireve account information at /AccountService/Accounts/{name}
- create a new account at /AccountService/Accounts
- modify an account at /AccountService/Accounts/{name}
- delete an account at /AccountService/Accounts/{name}
@RackHD/corecommitters @uppalk1 @tannoa2 @keedya
=> [redfish] AccountService functional tests

test/benchmark/utils/parser.py
Modify footprint benchmark parser.py to: 
1. further scan log folder to show not only time stamp but also case name
2. Write process list to log file for use by front end html pages
@RackHD/corecommitters @iceiilin @WangWinson
=> Modify footprint benchmark parser.py

test/config/amqp.py, test/modules/amqp.py, test/run.py
Pass --amqp option with exchange/queue parameters to listen continuously on exchange
Optional tool.  Take it or leave it.
@RackHD/corecommitters @zyoung51 @uppalk1 @tannoa2 @geoff-reid @keedya
=> Add AMQP listener mode utility

test/tests/api/redfish_1_0/managers_tests.py
The RackHD ethernet interface list returns the os named interfaces
instead of an index number.  Change the test to use the enumerated
values returned by the list interface command rather than the hard
coded '0' value.
=> [redfish] RackHD Manager support

test/README.md, test/tests/api/redfish_1_0/chassis_tests.py, test/tests/api/v1_1/amqp_tests.py, test/tests/api/v1_1/nodes_tests.py, test/tests/api/v1_1/obm_tests.py, test/tests/api/v1_1/os_install_tests.py, test/tests/api/v1_1/workflows_tests.py
- Adds OS installer test cases for CentOS, Ubuntu, ESXi, and SUSE OS installer workflows for 1.1 API.  Runs concurrently across all discovered nodes.
- Adds workflow to remove disk MBR and partitions on each node (runs concurrently)
- Some cleanup around group naming and priorities (mainly in API1.1 AMQP and OBM tests). 
- Some POST workflow refactoring under workflows_test module.
@RackHD/corecommitters @keedya @zyoung51 @tannoa2 @uppalk1 @iceiilin
=> Add OS installer regression tests

test/tests/api/v1_1/os_install_tests.py
@RackHD/corecommitters @keedya @uppalk1 @tannoa2 @zyoung51 
Updated to reflect changes that required explicit OBM options input.
=> Add default OBM service options to os-installer

test/modules/amqp.py, test/tests/api/v1_1/os_install_tests.py
- Set explicit timeout option per OS install test
- Set explicit installDisk
- Cleanup log output in default AMQP handler (format json)
=> OS installer timeout option and reformat default AMQP output

test/tests/api/v2_0/tags_tests.py
when a none enclosure node has no manufacturer info the tag based on its id will be tagged to not only the none manufacturer nodes but also the enclosure node, in this case the enclosure node didn't be used to tag but to test tags.
=> fix the bug: when a node with enclosure has no manufacturer, t case fails.

test/.dockerignore, test/Dockerfile
This will allow the python tests to be run when `docker-compose up` is executed. https://github.com/RackHD/RackHD/pull/265/files#diff-072e81fe88d9b23fe00fc189279936a6R39
Progress towards running our tests against a RackHD docker environment.
=> Adds Dockerfile to python tests

test/tests/api/v1_1/nodes_tests.py, test/tests/api/v2_0/skupack_tests.py, test/tests/api/v2_0/tags_tests.py
- Modify tags and skus to request the 'dmi' catalog instead of attempting
to parse the catalog array.  This resolves an issue where the 'dmi' was
not the first element in the array, and the tests would fail.
- Modify the 1.1 Delete:/nodes/:mac/dhcp/whitelist to only delete compute
type identifiers to align with the POST:/nodes/:mac/dhcp/whitelist test.
@RackHD/corecommitters @uppalk1 @keedya @tannoa2 @jlongever
=> Functional test fixes

test/tests/api/v2_0/obm_tests.py
@RackHD/corecommitters @BillyAbildgaard @srinia6 
Removed tests of API 2.0 OBM routes that will no longer exist when the following pull request is merged:
https://github.com/RackHD/on-http/pull/312
=> Remove obsolete OBM functional tests

test/tests/api/v2_0/nodes_tests.py, test/tests/api/v2_0/workflows_tests.py
Functional Test updates need for the https://github.com/RackHD/on-http/pull/313 to pass testing
I tested these changes locally and it fixed all failures seen in the above PR.
@RackHD/corecommitters @dalebremner @srinia6
=> Updating nodes/workflows functional tests

packer/README.md, packer/ansible/rackhd_local.yml, packer/ansible/roles/isc-dhcp-server/files/systemd-control.cfg, packer/ansible/roles/isc-dhcp-server/files/systemd-isc-dhcp-server, packer/ansible/roles/isc-dhcp-server/tasks/main.yml, packer/ansible/roles/node/tasks/main.yml, packer/ansible/roles/swagger/tasks/main.yml, packer/template-ubuntu-14.04.json, packer/template-ubuntu-16.04.json
1. Ubuntu 16.04 is released recently. update packer scripts for ubuntu 16.04. refer to https://github.com/chef/bento/blob/master/ubuntu-16.04-amd64.json
2. upgrade node 0.10 to the latest node 4 for both ubuntu  14.04 and 16.04. 
3. Adjust control network interface from 'eth1' to 'enp0s8'  for Ubuntu 16.04 (default name for virtualbox second NIC).  vagrant don't support systemd biosdevname setting(only support 'eth1'/...), workaround it using config file.
Updated
@RackHD/corecommitters @heckj @benbp @iceiilin
=> packer vagrant box using node 4 and based on ubuntu 16.04

test/tests/api/v2_0/workflows_tests.py
Supports/requires changes made in https://github.com/RackHD/on-http/pull/323
Replacing the use of the internal mongo `graph.id` field with the `graph.instanceId` attribute instead.
@RackHD/corecommitters @jlongever
=> Get workflow by instanceId, not mongo id

test/tests/api/v1_1/os_install_tests.py
Add user to users[] in options, required for ssh Validation task
depends on :https://github.com/RackHD/on-core/pull/173
=> OS Install Regression test failures for  ESXI 

test/tests/api/v1_1/os_install_tests.py
The undefined KVM option was causing a problem:
"
ApiException: (400)
Reason: Bad Request
HTTP response headers: HTTPHeaderDict({'Content-Length': '96', 'X-Powered-By': 'Express', 'Connection': 'keep-alive', 'ETag': 'W/"60-XK65W/Oe2Sdf6stTjyKPWQ"', 'Date': 'Tue, 12 Jul 2016 15:23:55 GMT', 'Access-Control-Allow-Origin': '*', 'Content-Type': 'application/json; charset=utf-8'})
HTTP response body: {"message":"Task.Os.Install.CentOS: JSON schema validation failed - data.kvm should
"
=> Fixing the centOS install test

test/tests/api/v1_1/os_install_tests.py
Use mounted ISO file for the test
@jlongever @zyoung51 @tannoa2 @brianparry @RackHD/corecommitters 
depends on: https://github.com/RackHD/on-tasks/pull/280
depends on : https://github.com/RackHD/on-http/pull/364
=> Update Ubuntu installation test

packer/ansible/rackhd_package.yml, packer/ansible/roles/node-legacy/tasks/main.yml
- no longer install legacy (node 0.10) packages
- install nodesource node4 packages
- removing ansible role for node 0.10
=> updating ansible playbook for node4

docker/monorail/config.json, packer/ansible/roles/monorail/files/config.json, packer/ansible/roles/remoterepos/tasks/main.yml
- needed for on-http install during source installation now
- duplicate in later role (swagger) that we might consider removing in that role, but dupe doesn't hurt ansible doing it's thing, and trying to keep the dependencies relevant to their roles to maintain good form there
=> adding libkrb5-dev library for NPM install

example/samples/install_ubuntu_payload_iso_full.json, example/samples/install_ubuntu_payload_iso_minimal.json
- Simply by downloading the ISO and mounting it to on-http static repo
as follows:
- mount -o loop /var/mirrors/ubuntu-14.04.4-server-amd64.iso on-http/static/http/ubuntu
=> Add Ubuntu install examples for using local mounted iso

test/tests/api/v2_0/lookups_tests.py, test/tests/api/v2_0/nodes_tests.py, test/tests/api/v2_0/skupack_tests.py, test/tests/api/v2_0/workflows_tests.py
Update functional tests codes, based on the on-http PR.  
**Depends on** PR https://github.com/RackHD/on-http/pull/389
All functional tests with the on-http changes PASS locally.
@benbp @keedya @BillyAbildgaard @brianparry @dalebremner @RackHD/corecommitters @zyoung51 @jlongever
=> Update functional test's HTTP codes

packer/ansible/roles/images/tasks/main.yml
requires https://github.com/RackHD/on-imagebuilder/pull/51 to be merged prior to this being fully operational (need the merge to generate binaries in bintray for this to work)
=> adding in monorail.intel.ipxe for NUC support

docker/monorail/config.json
Previously done in https://github.com/RackHD/RackHD/pull/147, not
migrated to docker config.
=> Remove 'current' from docker coreos proxy config

test/tests/api/v2_0/pollers_tests.py
* Expect either 200 or 204 status.
* Check appropriate data length depending on HTTP status.
* Remove handling for ApiError exception.
@RackHD/corecommitters @srinia6 @dalebremner @BillyAbildgaard @keedya @jlongever
=> Fix pollers test

packer/ansible/roles/build/tasks/main.yml
- enables vagrant instance to be used to generate/test packaging
=> extend build role to include deb packaging tooling

docker/files/Dockerfile
Since the `monorail.intel.ipxe` file is now built and uploaded to bintray by default, it should be added to the "files" container.
Reference #345
=> Add intel iPXE file to "files" docker container

test/tests/api/v2_0/workflows_tests.py
adding "label" in functional test because it's now a required field in the schema. 
dependent on https://github.com/RackHD/on-http/pull/449/
@RackHD/corecommitters @dalebremner @keedya @srinia6 @geoff-reid
=> updating functional tests

example/install_rackhd.sh
https://groups.google.com/forum/#!topic/rackhd/7W425hRyXdU
RackHD installation is not quite easy and fast. a ONE-KEY-Install is a good ask.
people can directly install by   `wget -qO- https://raw.githubusercontent.com/panpan0000/RackHD/one-key-quick-install/example/install_rackhd.sh  | sudo bash`
just combine the steps(install from package) in readthedocs, and make it a single script.
http://rackhd.readthedocs.io/en/latest/rackhd2.0/ubuntu_package_installation.html?highlight=install
NOTE: it's only tested in Ubuntu 14.04. and definitely,  it can't apply to other Linux distribution or even Ubuntu 16.04.later on , we will do OS switch-case in this script to make it workable in other OS.
the eth1 and IP 172.31.128.1 seems can't be easily modified. so I force check it at script beginning.
if …
=> Add a simple quick install RackHD script, which as a quick try for users (only for Ubuntu trusty for now)

example/samples/centos_iso_boot.json, example/samples/centos_iso_kvm_boot.json, example/samples/full_centos_mirror_boot.json, example/samples/install_suse_payload_minimal.json, example/samples/vQuanta_default_install_workflow.json, example/samples/vQuanta_default_workflow.json
The `version` is a required option for install-os which is defined in task-schema.
@RackHD/corecommitters @heckj @cgx027 @iceiilin @pengz1 @WangWinson
=> add the missing version for install-os sample payload

test/tests/api/v1_1/nodes_tests.py, test/tests/api/v2_0/nodes_tests.py
enhance https://github.com/RackHD/RackHD/issues/270
Import a external value **NODES_NUMBER** ,which means how many nodes are used for test.
Enhanced node discovery test case skip condition, only if all nodes are in mongodb this case skip.
@iceiilin @panpan0000 @RackHD/corecommitters    
Jenkins: depends on https://github.com/RackHD/on-build-config/pull/23
=> fix node discover test case issue: RackHD/RackHD issue #270

packer/ansible/rackhd_package.yml
The rackhd services will start after installation.
But rackhd is installed before loading config file and the config file takes no effect on rackhd services.
This PR move rackhd installation after loading config file.
@heckj @panpan0000 @iceiilin @anhou @yyscamper
=> fix: rackhd services start before load config

example/README.md, example/bin/monorail_rack, test/README.md
use PM2 instead of foreman to  manage rackhd process.
see GG https://groups.google.com/forum/#!topic/rackhd/UfyZ1v9Gdc4
This PR should be merged at the same time with https://github.com/RackHD/docs/pull/357  after new version vagrant box be updated.
Related PR
* https://github.com/RackHD/RackHD/pull/478  edit packer script, change foreman to pm2.
* https://github.com/RackHD/docs/pull/357 docs change
* https://github.com/RackHD/on-build-config/pull/31 edit Vagrantfile for smoke-test
@panpan0000
=> Edit readme, change foreman nf start to pm2 start rackhd.yml

test/fit_tests/common/fit_common.py
This is an update to the FIT common library that includes several required fixes:
- The primary change is to the appy_obm_settings(). This is a new routine to apply OBM settings in parallel rather than the old sequential routing. The legacy routine has been renamed to apply_obm_settings_seq(). This has code been tested for about two weeks in the MN lab.
- check_active_workflows() needed revision to be compatible with the new 'status' field in the workflows API JSON. OnRack 2.1 was branched before that change so the old '_status' field needs to be supported as well.
- restful() 'binary-put' and 'binary-post' content type was changed to "application/x-www-form-urlencoded" for compatibility with API 2.0. Now the /api/2.0/skus/pack upload will work.
- Line 217 still had a reference to the …
=> Updates to FIT test common library

packer/ansible/rackhd_ci_builds.yml, packer/ansible/rackhd_release.yml, packer/ansible/roles/rackhd-ci-builds/tasks/main.yml, packer/ansible/roles/rackhd-release/tasks/main.yml, packer/ansible/roles/setuptools/tasks/main.yml, packer/scripts/firstuser.sh, packer/template-packages.json
Add 
```
ansible/rackhd_ci_builds.yml
ansible/rackhd_release.yml
ansible/roles/rackhd-ci-builds/
ansible/roles/rackhd-release/
```
support ci-builds and release builds.
Template file `template-packages.json` is changed to accept more vars.
see config and usage in executed shell in http://rackhdci.lss.emc.com/job/vagrant-build-bri/
About change of `firstuser.sh`:
- After installing rackhd, the eth1 hasn't been up. So services can't start normally then stopped abnormally, but left PID files. So though `firstuser.sh` start eth1, services still can't start because of PID files. Delete those files solvedthis issue.
=> support release, do ci-builds and release based on template-package.json

example/samples/install_windows_payload_full.json
Device name doesn't stay consistent in Windows OS on Jenkins slave 5. So changing the name to MAC address.
=> Changing device name to pass MAC address 

packer/HWIMO-BUILD, packer/ansible/rackhd_package.yml, packer/ansible/roles/config_admin_ip/files/config_IP_with_OVF_ENV.sh, packer/ansible/roles/config_admin_ip/tasks/main.yml
**Background**
Default RackHD OVA( same as Onrack) eth0(primary admin NIC) are configured as DHCP.
**How about  enviroment **without DHCP** on admin port (eth0) ?**
For many user scenario,   the OVA will be deployed into a network without DHCP against its eth0.
to enable this VM with static IP, before anyone can remote talk to this RackHD instance : then it will require manual operation: going to VMWare Console, and login into VM, modify the /etc/network/interface to re-configure that VM to static IP ....
A more automatic way is definitely needed.
---
**Summary of Implementation**
1. modify the OVF template file(XML) , to inject customized fields 
2. when deploying the OVA, pass IP/DNS/Gateway..etc parameter to ovftool or vCenter GUI
3. when the VM boot up , there's a script will be run …
=>  Auto Config primary IP address, when OVA is deployed 

packer/ansible/roles/pm2/files/rackhd-pm2-config.yml
```rackhd-pm2-config.yml``` use absolute path of "/home/vagrant/....." 
This will lead failure when user install rackhd according to http://rackhd.readthedocs.io/en/latest/rackhd/ubuntu_source_installation.html.
=> change absolute path in rackhd-pm2-config.yml to relative path

test/fit_tests/README.md, test/fit_tests/Vagrantfile, test/fit_tests/config/global_config.json
This PR contains a new 'Vagrant' RackHD installer for workstation-based development and test environments.
This update consists of two files:
test/fit_tests/Vagrantfile
test/fit_tests/README.md
Vagrantfile is a script that executes the following procedures:
- downloads and starts a Ubuntu 16 template from Vagrant Atlas as server
- runs the FIT source installer to load the latest RackHD on Ubuntu server
- configures RackHD to run on the Vagrant host
- starts up RackHD
- loads SKU packs
- downloads and starts InfraSim Quanta D51 simulator
The README.md file has detailed instructions on how to configure and run the script.
This PR is dependent upon the following PRs to run properly:
https://github.com/RackHD/RackHD/pull/491
https://github.com/RackHD/RackHD/pull/487
This has been tested using …
=> Rac 249 Vagrant installer

test/fit_tests/config/global_config.json, test/fit_tests/deploy/rackhd_package_install.py, test/fit_tests/deploy/rackhd_source_install.py
This PR is to update the RackHD installer scripts as part of Phase 1 of RackHD Test Framework:
https://groups.google.com/forum/?hl=en#!topic/rackhd/cscQ2T20Uxs
Files updated are:
test/fit_tests/deploy/rackhd_source_install.py  - installs RackHD from source using rackhd_local.yml 
test/fit_tests/deploy/rackhd_package_install.py  - installs RackHD from packages using rackhd_package.yml 
test/fit_tests/config/global_config.json - contains repo and branch selections for source installer
The new installers are intended meet the following objectives:
- run either remote or local on management server (default)
- run from ESXi-based or Virtualbox-based management server VMs
- ability to run behind proxy
- run from Ubuntu 16 or Ubuntu 14 (see exception below)
- source installed from selectable …
=> Updated rackHD installer scripts

test/fit_tests/tests/rackhd20/test_rackhd20_api_nodes.py, test/fit_tests/tests/rackhd20/test_rackhd20_api_tags.py
This fixes three test failures related to /api/2.0/nodes requiring a type field in its POST block.
@gpaulos @stuart-stanley
=> Update POST /api/2.0/nodes related tests to provide now required 'type' field.

packer/ansible/roles/isc-dhcp-server/files/config_isc-dhcp-server.sh, packer/ansible/roles/isc-dhcp-server/tasks/main.yml, packer/scripts/addnetif.sh, packer/scripts/dep.sh, packer/scripts/firstuser.sh, packer/template-ubuntu-14.04.json, packer/template-ubuntu-16.04.json
this is a hot fix https://github.com/RackHD/RackHD/pull/508/
because any script in packer ( either in packer provision or ansible) runs inside the created VM,
so the shell library file should be copied to VM first, before invoking it.
@changev @cgx027 @anhou @yyscamper
=> Bug fix: move library script to VM's /tmp/

packer/template-ubuntu-14.04.json, packer/template-ubuntu-16.04.json
What's up:
1. it's a bug  fix for 14.04 packer script. the ```get_nic_name_by_index.sh``` file copy should happen before ```addnetif.sh```
2. change the admin (eth1) configuration before ansible playbooks( install rackhd..etc)
Test Done:
successful build a 14.04 OVA , and verify RackHD service running well for that OVA
@changev  @yyscamper  @anhou
=> adjust the order of packer provisioning: config eth1 before ansible

example/Vagrantfile
Currently if the repo dir you specify via the environment is on-core on on-tasks it doesn't get mapped due to the mapping being in the else clause of the special-casing that maps them into the node_modules directories of the other projects.
This fixes that, allowing easier development of on-core and on-tasks.
Fixes #499
=> Always map the repo dir.

example/config/rsyslog_rackhd.conf.example
Create rsyslog configure file example.
A new feature is added to OS installation to enable node to send OS installation syslog to RackHD server. This PR created a rsyslog configure that enables RackHD server rsyslog to received syslog from nodes and store logs in /var/log/rackhd/ with <node_ip>_<date> format.
=> Create rsyslog configure file example

test/config/amqp.py, test/tests/api/v2_0/__init__.py, test/tests/api/v2_0/sel_alert_poller_tests.py, test/tests/api/v2_0/skupack_tests.py
-Generate and post the skupacks that create the alert defenition
-Validate that the selEntires pollers are created fo the compute
node after the skupack si posted
-validate the basic alert functionality of the poller by listining on AMQP
-validate the RackHD decodes the raw sel read correctly
("Event Type Code" and "Sensor Type Code")
-Validate the sel poller alert can handle the overflow option in the sel
-validate that the poller can handle when the sel is cleared
-validate that poller can digest the data of the whole sel log at once and entries are dropped
=> WIP: Add tests for sel poller alerts

packer/ansible/roles/isc-dhcp-server/files/config_isc-dhcp-server.sh
It's option 1, option 2 is https://github.com/RackHD/RackHD/pull/522
**Background**
there's a common script(get_nic_name_by_index.sh) to be invoked by both ```packer/scripts/``` and ```packer/ansible/````
simply putting the common-script in either place , will make the other can't access this common-scripts.
Example, packer will only copy content under "packer/ansbile" to VM's staging dir(/tmp/packer-provisioner-ansible-local), so the common script will never be found by ansible.
**Previous Fix Attempts**
- I used packer provision scripts(running before ansible) to copy the common-script to VM's filesystem. but it makes ansible has to be depend on the packer , and can't run alone
- I tried to leverage some packer parameter to workaround and upload the common script to VM's filesystem , …
=> RAC-800: Make the Ansible can run without Packer ( option #1)

packer/ansible/roles/isc-dhcp-server/tasks/main.yml
Bugfix for RAC-800
Ansible RackHD installers were failing on the isc-dhcp-server task when logged in as anything other than root.
Problem is using "~/" in path which is interpreted differently under different circumstances. Should always use "{{ ansible_env.HOME }}" to reference home dir.
One file changed:
packer/ansible/roles/isc-dhcp-server/tasks/main.yml
=> RAC-800 Changed path references from ~/ to {{ ansible_env.HOME }}

test/modules/worker.py
fixing case where task was timing out and not reporting a failure
In old code task was getting removed and therefore wasn't reporting when `task.timeout = True`
@RackHD/veyron
=> fixing false positive test scenario

packer/HWIMO-BUILD, packer/ansible/rackhd_ci_builds.yml, packer/ansible/rackhd_release.yml, packer/ansible/roles/config_admin_ip/files/config_IP_with_OVF_ENV.sh
It depends on https://github.com/RackHD/RackHD/pull/530
-----
**Background**
the "IP setting from OVF Template" feature sometimes fail in 14.04 VM, for first boot.
error signature: 
the ifdown/ifup in ```packer/ansible/roles/config_admin_ip/files/config_IP_with_OVF_ENV.sh``` is very slow and finally fail.
error message:
```Ifdown : waiting for lock on /run/network/ifstate.eth0```
----
**root cause**
in Ubuntu 14.04, /etc/init/network**.conf will "ifup" the eth0 during booup( trying DHCP) , and it's non-blocking operation. 
so if eth0 in a non-DHCP network, the DHCP attemp will last for 5 mins(?). so even system boot up when login prompt shown, the "ifup"  process still running in the background.
the latter ifdown/ifup operation will fail.(  in the /run/network/ folder, it will shows eth0 …
=> Kill dhcp attempt during first boot, if user assign admin ip in ovf template

test/common/fit_common.py, test/config/auth.py, test/config/global_config.json, test/config/settings.py
This is a change that moves towards combining cit and fit
configurations.  This will not be the final solution but allows
both cit and fit to read from a common file.
Note: if any Jenkins jobs are using 'run.py --config=X.ini', we will need to update those to make use of the different configuration file.
Tested with:
python run.py --show-plan
python run.py --group="pollers_api2.tests"
python run.py --config="local.json" --group="pollers_api2.tests"
python run_tests.py -stack 1 -test util/display_rackhd_nodes.py
python run_tests.py -stack 1 -test deploy/rackhd_stack_init.py -list
python run_tests.py -stack 1 -test tests/compute/test_rackhd11_computenode_pollers.py
@RackHD/corecommitters @gpaulos @johren @larry-dean  @stuart-stanley @amymullins
=> Encapsulate config.ini inside global_config.json.

test/common/mkcfg.py, test/common/singleton.py, test/config/generated/.gitignore, test/requirements.txt
new modules:
common/mkcfg.py
Manages a RackHD test configuration
Singleton object creation:
cfg = mkcfg(config_dir, json_config_files, arg_list)
Access the singleton
cfg = mkcfg()
Methods:
add : adds additional test configurations to an existing
mkcfg object.  Individual dictionary values will be
overwritten by the inbound json_config_file values.
Example:
cfg = mkcfg(config_dir, json_config_files, arg_list)
cfg.add(stack_config_file)
get : returns the config dictionary
Example:
myconfig_dict = cfg.get()
get_path : returns the config dictionary
Example:
config_path = cfg.get_path()
destroy : destroys the singleton to allow for a new configuration
Example:
cfg.destroy()
common/singleton.py
Implements a class used to assist in creating singletons
requirements.txt
Add jsonschema and …
=> Adds mkcfg module useful for managing RackHD configurations.

test/__init__.py, test/common/fit_common.py, test/requirements.txt, test/tests/api-cit/README.md, test/tests/api-cit/v2_0/nodes_tests_fit.py, test/util/display_rackhd_nodes.py
This is a change that moves towards combining cit and fit testing.  This PR adds the nosedep package into the mix used by fit_common.py/run_tests.py and a first draft of a script nodes_tests.py converted into the FIT format.  The updates don't affect any running CIT tests that use run.py.
Tested with:
python run.py --show-plan
python run.py --group="pollers_api2.tests"
python run_tests.py -stack 1 -test util/display_rackhd_nodes.py
python run_tests.py -stack 1 -test deploy/rackhd_stack_init.py -list
python run_tests.py -stack 1 -test tests -group smoke
python run_tests.py -stack 1 -test tests/api-cit/v2_0/nodes_tests_fit.py -list
python run_tests.py -stack 1 -test tests/api-cit/v2_0/nodes_tests_fit.py:NodesTests.test_07_node_catalogs
python run_tests.py -stack 1 -test …
=> fit phase 1 - Add nosedep package and converted CIT test script example

test/HWIMO-BUILD
This PR contains an updated HWIMO-BUILD script to support Jenkins RackHD FIT automation.
Removed obsolete parameters and OnRack-specific code.
Added new -config parameter to support config directory selection (required for MN Jenkins).
=> Updated HWIMO-BUILD for RackHD Jenkins requirements

test/.gitignore, test/HWIMO-BUILD, test/README.md, test/Vagrantfile, test/common/fit_common.py, test/requirements.txt, test/run_tests.py, test/setup.cfg, test/stream-monitor/.gitignore, test/stream-monitor/README.md, test/stream-monitor/flogging/__init__.py, test/stream-monitor/flogging/infra_logging.py, test/stream-monitor/flogging/logger_sets.py, test/stream-monitor/mkenv.sh, test/stream-monitor/requirements.txt, test/stream-monitor/setup.py, test/stream-monitor/sm_plugin/__init__.py, test/stream-monitor/sm_plugin/stream_monitor.py, test/stream-monitor/stream_sources/__init__.py, test/stream-monitor/stream_sources/log_type.py, test/stream-monitor/stream_sources/monitor_abc.py, test/stream-monitor/test/support/stream-base/one_pass/test_one_pass.py, test/stream-monitor/test/support/stream-base/two_pass/test_two_pass.py, test/stream-monitor/test/support/stream-source/logging/one_pass/test_one_log_pass.py, test/stream-monitor/test/support/stream-source/logging/two_pass/test_two_log_pass.py, test/stream-monitor/test/test_log_stream.py, test/stream-monitor/test/test_stream_base.py, test/tests/rackhd11/test_rackhd11_api_catalogs.py
Change to common/fit_common.py
* bring in new "flogging" (fit-logging) module from stream-monitor plugin space
* added a merged file to flogging (all_all).
* adjust run_nose() method to:
** fix: not use lucky-scoping to get access to noseopts variable
** converted invocation to use built environment and args set (rather than monster subprocess string)
*** env passed in via official api
*** noseargs passed in the same
*** converted from dangerous string to list-of-args
* added run_from_module() method (see changes to tests/rackhd11/test_rackhd11_api_catalogs.py)
Everything under stream-monitor is basically the plugin from PR https://github.com/stuart-stanley/nose-observer-plugin/pull/1.
It contains four sub-dirs and some support files. This is implemented as a plugin for nose!
* support …
=> rac-3802 bring larval logging and stream monitors to public space

test/tests/rackhd11/test_rackhd11_api_templates.py, test/tests/rackhd20/test_rackhd20_api_templates.py
The api/x.x/templates command has been revised since the original tests were checked in. 
This PR applies corrections to these tests.
The GET api/x.x/templates command is no longer valid without a name spec.
=> Bugfix api templates

debian/control, debian/postinst
**Background**:
Now the static files built by on-imagebuilder is out of version control.
And RackHD always downloads these files from a fixed url.
We are going to release on-imagebuilder.deb to control the version of these static files.
RackHD will depend on the package to get specified version of static files.
**Test**:
Build debian packages:
http://rackhdci.lss.emc.com/job/BuildRelease/job/Build/job/debian-build/
Install rackhd (depends on on-imagebuilder) on clean ubuntu 14.04 and 16.04 successfully.
=> RackHD debian package depends on on-imagebuilder.deb

test/common/fit_common.py
Tested the following:
python run.py --show-plan
python run.py --group="pollers_api2.tests"
python run_tests.py -config dellemc-test/config-mn -stack 1 -test util/display_rackhd_nodes.py
python run_tests.py -config dellemc-test/config-mn -stack 1 -test deploy/rackhd_stack_init.py -list
python run_tests.py -config dellemc-test/config-mn -stack 1 -test tests/compute/test_rackhd11_computenode_pollers.py
python run_tests.py -config dellemc-test/config-mn -stack 1 -test tests -group smoke
@RackHD/corecommitters @gpaulos @hohene
=> Add HOME into environment passed through subprocess.

test/tests/rackhd11/test_rackhd11_api_misc.py, test/tests/rackhd20/test_rackhd20_api_misc.py
These tests are causing errors in the CIT/FIT production jobs because the production RackHD deployment does not install the docs pages. 
This just removes the tests from the smoke and regression jobs. They can still be run individually if desired.
@hohene @johren @jimturnquist @diontje @larry-dean @keedya
=> Remove API docs tests from smoke/regression

test/deploy/rackhd_stack_init.py
This PR suppresses a spurious test failure in the CIT/FIT Jenkins run. 
Removed the assert for IMPI node restart because the arp table is empty on the Vagrant host. This is not a test but a setup step which is not necessary in the CIT/FIT environment. If the call to fit_common.power_control_all_nodes() returns nonzero, it will print a warning but not issue an assert. 
@hohene @johren @jimturnquist @diontje @larry-dean @keedya
=> Update stack init poweron nodes

packer/ansible/rackhd_ci_builds.yml, packer/ansible/rackhd_release.yml
@changev @PengTian0 
Background:
the motivation of ConfigAdminIP feature  can be refereed in https://github.com/RackHD/RackHD/pull/484
later , more ansible playbook was introduced but this ConfigAdminIP feature didn't get into them.
FAQ:
it will not impact user who directlly run ansible-playbook ( not packer). the configAdminIP scripts during system startup will exist, because VMWareTool will not detect any OVF Template Variable.
What's Test:
use Jenkins job to build OVA using ansible ```rackhd_ci_builds.yml```
http://rackhdci.lss.emc.com/job/Maglev-BRI-Test/job/BuildRelease/job/ova-build/33/console
=> Add the ConfigAdminIP step to other ansible scripts

test/.gitignore, test/common/fit_common.py, test/mkenv.sh, test/setup.cfg, test/tests/rackhd11/test_rackhd11_api_catalogs.py
General solution: make it so the places where infra-logging gets imported ONLY happen when running FIT tests. Changes made to do this:
* remove with-stream-monitor from setup.cfg. This keeps nose from auto-bringing in stream-monitor which in turns brings in the new logging infrastructure
* remove access to infra-logging from fit_common.py import-time. (This doesn't actually impact CIT interaction, but does keep us from double-rotating the log-dir and/or rotating them on "run_test.py --help"
* added "--with-stream-monitor" to sub-process invocation within fit-common. That means when we DO finally kick off the real nosetests via run_tests.py , the plugin is enabled and flogging comes on line
* changed tests/rackhd11/test_rackhd11_api_catalogs.py to directly grab flogging. See below for …
=> RAC-3883 keep new infra-logging from interfering with unconverted CIT tests' output

packer/template-ubuntu-14.04.json, packer/template-ubuntu-16.04.json
Otherwise build will fail in low performace machine.
boot-wait-time is the wait time for pc to enter CD/ISO install interface since power on.
If the machine performace is too bad, 10s will be not enough, and OS installation will hang at some interface.
And then packer build will hang forever.
```
==> vmware-iso: Starting HTTP server on port 8377
==> vmware-iso: Starting virtual machine...
vmware-iso: The VM will be run headless, without a GUI. If you want to
vmware-iso: view the screen of the VM, connect via VNC without a password to
vmware-iso: 127.0.0.1:5931
==> vmware-iso: Waiting 10s for boot...
==> vmware-iso: Connecting to VM via VNC
==> vmware-iso: Typing the boot command over VNC...
==> vmware-iso: Waiting for SSH to become available...               
```
SSH will never become …
=> extend boot wait time

test/stream-monitor/flogging/__init__.py, test/stream-monitor/flogging/infra_logging.py, test/stream-monitor/mkenv.sh, test/stream-monitor/requirements.txt, test/stream-monitor/sm_plugin/__init__.py, test/stream-monitor/sm_plugin/stream_monitor.py, test/stream-monitor/test/test_infra_logging.py, test/stream-monitor/test/test_stream_base.py
NOTE: this is a rebase of https://github.com/RackHD/RackHD/pull/554 , since I managed to completely mess up trying to rebase THAT pr. @hohene and @gpaulos have +1'ed that PR. If you two could "approve" this rebase, and then we just need a @RackHD/corecommitters please.
Primary changes:
* changed abs symlink to be a link within the same dir
* added logger_get_logging_dir to infra-logging (for test use)
TDD changes:
* added test_infra_logging.py as location for tests of the infra-logging stuff.
** added setup to ask infra-logging (via the logger_get_logging_dir from above) where to look
** added canary test to make sure tests are being invoked
** added test to check the run_last.d is there, is a symlink, and points to something valid
** added fail-before-change, pass-after-change test to …
=> rac-3789 run_last.d symlink should be relative rather than absolute

test/stream-monitor/sm_plugin/stream_monitor.py, test/stream-monitor/stream_sources/log_type.py, test/stream-monitor/test/plugin_test_helper.py, test/stream-monitor/test/support/stream-source/logging/backtrace/test_backtrace.py, test/stream-monitor/test/support/stream-source/logging/stderr_errcap/test_stderr_errcap.py, test/stream-monitor/test/support/stream-source/logging/stderr_failcap/test_stderr_failcap.py, test/stream-monitor/test/support/stream-source/logging/stderr_nocap/test_stderr_nocap.py, test/stream-monitor/test/support/stream-source/logging/stdout_errcap/test_stdout_errcap.py, test/stream-monitor/test/support/stream-source/logging/stdout_failcap/test_stdout_failcap.py, test/stream-monitor/test/support/stream-source/logging/stdout_nocap/test_stdout_nocap.py, test/stream-monitor/test/support/stream-source/logging/two_pass/test_two_log_pass.py, test/stream-monitor/test/test_log_stream.py, test/stream-monitor/test/test_stream_base.py
This is a re-submit of https://github.com/RackHD/RackHD/pull/558, which included the symlink changes in it (which came in under their own PR). @hohene and @gpaulos approved the nose-capture part of that PR already. @RackHD/corecommitters for merging please!
Note that the following stories have been opened to round out the abilities added here:
* RAC-3869 to handle retro-grabbing of DEBUG level log output and such
* RAC-3870 to getting the progress line data into a log entry instead of raw output
* RAC-3875 to capture data _after_ an error has occured (like for tearDown and such)
Note: xunit, capture, and logcapture all do similar things, but everyone reports AFTER all the tests are done. Handy for style of use, really annoying for say Jenkins jobs!
Primary changes:
* Basically stole the …
=> RAC-3817 capture nose stuff

docker/.env, docker/README.md, docker/docker-compose.yml
Add ${TAG} in docker-compose, support:
```
$ cd RackHD/docker                            # TAG can be a release version, if not set default: latest
$ sudo TAG=${TAG} docker-compose pull         # Download prebuilt docker images.
$ sudo TAG=${TAG} docker-compose up           # Create containers and Run RackHD and ELK.
```
if just
``` 
sudo docker-compose pull  
```
docker-compose will get default value of ${TAG} in .env .
=> [skip ci]modifydocker-compose.yml to support release/ci-builds

packer/template-ubuntu-14.04.json, packer/template-ubuntu-16.04.json
Otherwise build will fail in low performace machine.
boot-wait-time is the wait time for pc to enter CD/ISO install interface since power on.
If the machine performace is too bad, 10s will be not enough, and OS installation will hang at some interface.
And then packer build will hang forever.
```
==> vmware-iso: Starting HTTP server on port 8377
==> vmware-iso: Starting virtual machine...
vmware-iso: The VM will be run headless, without a GUI. If you want to
vmware-iso: view the screen of the VM, connect via VNC without a password to
vmware-iso: 127.0.0.1:5931
==> vmware-iso: Waiting 10s for boot...
==> vmware-iso: Connecting to VM via VNC
==> vmware-iso: Typing the boot command over VNC...
==> vmware-iso: Waiting for SSH to become available...               
```
SSH will never become …
=> add ova build boot wait

test/tests/api/v2_0/__init__.py, test/tests/api/v2_0/os_install_tests.py, test/tests/api/v2_0/workflows_tests.py
adding 2.0 OS Install regression tests.  These tests perform installs with the 2.0 API instead of the 1.1
@RackHD/veyron 
note: The OS installs worked locally and I also tried them on the new Jenkins setup
=> adding 2.0 OS regression tests

test/requirements.txt
In Jenkins, "POST:/nodes/" of api 1.1 in CIT always fails with the error message "connection abort" in these two days.
It is found that urllib3 used by on_http_1.1 python client releases a new version yesterday (see https://pypi.python.org/pypi/urllib3). Fix the version used for cit to the older one solves the problem.
It can be a temp solution until we verify the newer version of urllib3 works for our system.
=> fix urllib3 version in cit to fix api 1.1 post_nodes as a temp solution

test/config/amqp.py, test/tests/api/v2_0/sel_alert_poller_tests.py
modify test case to align with the new event format
modify sel alert test case to use WorkerThread to control the timeout value for amqp listener
Jenkins: depend on https://github.com/RackHD/on-tasks/pull/391 https://github.com/RackHD/on-core/pull/250
=> adjust sel alert test in cit api 2.0 test to align with new event format

test/requirements.txt
The following showed during recent (like 1/23/17ish) new checkouts of FIT where the mkenv was run on a ubuntu 16 box:
*** Using config file: dellemc-test/config-mn/generated/fit-config-20170124-151936
/emc/ohrenj/work/RackHD/test/.venv/fit/local/lib/python2.7/site-packages/nose/plugins/manager.py:395: RuntimeWarning: Unable to load plugin nosedep = nosedep:NoseDep: No module named extern.six RuntimeWarning)
Usage: nosetests options
Problem tracked to version 34.0.x of setuptools. Other folk are hitting similar issues. Until this stabalizes, pin the setuptools version to 33.1.1 (last version before 34.0.0 came out). @larry-dean: we may want to let zithrax know, since he will probably have others hitting this!
Testing:
* before/after : python run_tests.py -stack vagrant -list worked on mac …
=> rac-4044 upstream updates appear to have broken FIT's run_tests.py

test/deploy/os_ova_install.py
Fixed OVA installer for new FIT configuration system.
Multiple VM deployments now seed off of the 'ovamac' key in the stack config.
@hohene @jimturnquist @johren @larry-dean
=> Update deploy/os_ova_install.py multiple VMs routine

test/deploy/rackhd_source_install.py
Fixed source installer for new FIT configuration system.
NOTES:
lines 20-21: removed reference to deprecated -ora arguments
line 127 - increased ansible installer timeout for Vagrant deployments which often time out
line 133: revision to accommodate docker deployments
lines 89-100: removed explicit repo list, instead harvest repo list from config in line 97
lines 208-266: using generated 'config.json' from FIT config.
@hohene @jimturnquist @johren @larry-dean
=> Update deploy/rackhd_source_install.py for new FIT configuration

test/config/install_default.json
MN proxy settings inadvertently got included into the default public FIT config. This is causing the deployment scripts to fail outside of MN lab. Please review and merge quickly.
@johren @jimturnquist @hohene
=> Fix proxy settings in config/install_default.json

test/Vagrantfile
Recent changes to FIT broke the Vagrant installer.
These changes fix Vagrantfile script.
NOTES:
lines 37-38: the echo at the end of the line makes sure that each line returns a zero exitcode. Vagrant stops when a non-zero exit code is detected.
line 33: added package required for Python modules
@hohene @jimturnquist @johren @larry-dean
=> Updated Vagrantfile to conform to new FIT system

test/README.md, test/common/fit_common.py, test/stream-monitor/flogging/README.md, test/stream-monitor/flogging/__init__.py, test/stream-monitor/flogging/infra_logging.py, test/stream-monitor/flogging/infra_logopts.py, test/stream-monitor/flogging/logger_sets.py, test/stream-monitor/sm_plugin/stream_monitor.py, test/stream-monitor/stream_sources/log_type.py, test/stream-monitor/test/log_stream_helper.py, test/stream-monitor/test/plugin_test_helper.py, test/stream-monitor/test/test_infra_logging.py, test/stream-monitor/test/test_log_stream.py, test/stream-monitor/test/test_logopts.py
This adds control of the levels to the new logging infra. This is a first step, and
is focused mainly on the controls via the nose-plugin options, but with some wiring
for (temporary) to run_test.py's -v specturm. (rac-3984 will dig into that further).
Alas, this is a fairly big change-set. The bulk of what was added can be summed up with
the following --help chunk:
listing log settings:
--sm-list-logging   list logging settings
--sm-list-level=LIST_LOGGING_LEVEL
detail level if --list-logging is used
setting log options:
note: both 'logger-name's and 'handler-name's can contain wild-card
characters to match multiple items.
--sm-set-logger-level=('logger-name', 'level-name-or-value')
Set a logger's capture threshold. Loggers are
evaluated before handlers. …
=> rac-3777 verbosity ctl

.flake8
import statements are not always at the top of files within
RackHD/test.  This problem will be solved at some time in the
future.  For now, the python module pathing to test and test/common
needs to appear before statement like 'import fit_common'
@hohene
=> Add an exclusion for flake8 E402

.flake8, test/templates/fit_test_template.py, test/templates/run_wrapper_template.py
Added examples for fit_common api calls, dependencies, and base logging.
Templates can be used as a starting point for creating new fit tests.
=> RAC-4138 - Updated the test template files to match the current framework.

test/mkcheck.sh, test/stream-monitor/flogging/infra_logging.py, test/stream-monitor/flogging/infra_logopts.py, test/stream-monitor/flogging/logger_sets.py, test/stream-monitor/setup.py, test/stream-monitor/sm_plugin/__init__.py, test/stream-monitor/sm_plugin/stream_monitor.py, test/stream-monitor/stream_sources/__init__.py, test/stream-monitor/stream_sources/log_type.py, test/stream-monitor/test/log_stream_helper.py, test/stream-monitor/test/plugin_test_helper.py, test/stream-monitor/test/support/stream-base/two_pass/test_two_pass.py, test/stream-monitor/test/support/stream-source/logging/backtrace/test_backtrace.py, test/stream-monitor/test/support/stream-source/logging/one_pass/test_one_log_pass.py, test/stream-monitor/test/support/stream-source/logging/stderr_errcap/test_stderr_errcap.py, test/stream-monitor/test/support/stream-source/logging/stderr_failcap/test_stderr_failcap.py, test/stream-monitor/test/support/stream-source/logging/stderr_nocap/test_stderr_nocap.py, test/stream-monitor/test/support/stream-source/logging/stdout_errcap/test_stdout_errcap.py, test/stream-monitor/test/support/stream-source/logging/stdout_failcap/test_stdout_failcap.py, test/stream-monitor/test/support/stream-source/logging/stdout_nocap/test_stdout_nocap.py, test/stream-monitor/test/support/stream-source/logging/two_pass/test_two_log_pass.py, test/stream-monitor/test/test_infra_logging.py, test/stream-monitor/test/test_log_stream.py, test/stream-monitor/test/test_logopts.py, test/stream-monitor/test/test_stream_base.py
Went through and fixed all mkcheck errors down in stream-monitor.
No functional change, and self-tests have been re-run.
Well, technically, there was some incorrectly named test-classes that were hiding three tests. These now pass.
Also fixed copyrights on any file I touched and mkcheck.sh itself for Reasons(tm)
@RackHD/corecommitters @johren @jimturnquist
=> RAC-4205 cleanup stream monitor hound errors

test/tests/api/v2_0/nodes_tests.py, test/tests/rackhd20/test_rackhd20_api_nodes.py
In support of:
RackHD/on-tasks#394
RackHD/on-core#252
RackHD/on-http#570
=> Remove SNMP settings from node

test/tests/api/v2_0/nodes_tests.py
Relates to: https://github.com/RackHD/on-http/pull/551
Relates to: https://github.com/RackHD/RackHD/pull/600
This PR is to remove a CIT test which is causing this PR to fail - https://github.com/RackHD/on-http/pull/551
The above PR corrects a broken API. That PR won't pass because this CIT test fails. When making a PR to fix that CIT test the new test fails without the fixed API. I attempted using on-multi to address the mutual dependencies and was unsuccessful.
My hopes for this PR is to comment out the single failing test. See that Jenkins passes. Remove the test and push the PR up. Merge the API PR which behaves correctly. Then add an appropriate CIT test which is represented in this PR - https://github.com/RackHD/RackHD/pull/600
Please let me know if there's a better way forward than …
=> RAC-1984 Removing failing CIT test for dependent PR

test/README.md, test/common/fit_common.py, test/config/credentials_default.json, test/config/stack_config.json, test/deploy/os_ova_install.py
This is a resubmit of PR that renames 'ora' to 'rackhd_host' in reference to the appliance hostname or IP address for RAC-3711. Also removes numerous references to 'onrack'.
Tested on deployments and smoke test.
Please merge https://eos2git.cec.lab.emc.com/OnRack/dellemc-test/pull/10 after merging this PR.
@johren @hohene @jimturnquist @larry-dean
=> Commit RAC-3711-ora-reference-to-rackhd_host

test/tests/rackhd11/test_rackhd11_api_config.py, test/tests/rackhd20/test_rackhd20_api_config.py
This is a bugfix for the API config tests that were using a deprecated config key 'CIRDNET' and was causing failures under certain circumstances. This is causing the errors in the MN Smoke Test.
Removed the check for the  'CIRDNET' key.
Changed the patch test to a benign config key 'logColorEnable', which is a Boolean with two states. Added an assert to verify that the patch actually was applied, then return the config to the initial state.
Also removed the soon-to-be-deprecated 'verbosity' stuff.
@johren @hohene @jimturnquist @larry-dean @stuart-stanley
=> RAC-4233 Bugfix API config tests

docker/README.md
Otherwise, es container won't run normally
```max virtual memory areas vm.max_map_count [65530] likely too low, increase to at least [262144]```
=> [skip ci]docs: make sure vm.max_map_count >= 262144

test/common/fit_common.py
This change tries to prevent the annoyingly common situation of cutting and pasting something that replaces a '-' with a unicode en-dash. The code does:
* tries to substitute certain known culprits.
* blows up if there are still unicode characters that won't convert to ascii when the substitutions are done.
There are probably more we could substitute, but this at least stops you from spending all day trying to figure out why something is subtely not working!
Removed a few imports from fit_common as well (They were not being used by something importing fit_common either!)
Added a NOQA: imported but unused for "unittest", which IS used by a ton of stuff via the fit_common import.
@RackHD/corecommitters @jimturnquist @gpaulos @hohene @diontje
=> rac-44440-unicode-in-test-run-arguments

docker/README.md, docker/docker-compose-centos-dev.yml, docker/docker-compose-dev.yml, docker/docker-compose-mini-dev.yml, docker/docker-compose-mini.yml
https://rackhd.atlassian.net/browse/RAC-4356
This PR:
* Remove ```build: ../on-imagebuilder``` in ```*.yml``` files, prevent users to rebuild time costly ```rackhd/files``` when unecessary.
* Add ```*-dev.yml``` contains ```build: ../on-imagebuilder``` for users to rebuild ```rackhd/files``` when necessary.
* Enhance the docs to tell when should rebuild ```rackhd/files```  and how.
@panpan0000 @keedya @amymullins
=> [skip ci]add docs and yml for advanced rackhd/files build

.gitignore, test/common/fit_common.py, test/config_templates/corosync_config, test/deploy/rackhd_ha_install.py
Configures the control network, DHCP, /etc/hosts, and hostname on all nodes in the cluster.
Checks the corosync and pacemaker status to verify that we have created a happy cluster.
Had to modify fit_common.remote_shell and fit_common.scp_file_to_ora to pass in a VM number.
Defaults to node 1.
Tested by running the following with 3 and 4 node clusters.
```
python ./run_tests.py -test deploy/os_ova_install.py -stack 4 -template http://mirrors.hwimo.lab.emc.com/mirrors/ova/ha-ubuntu-1604.ova -config dellemc-test/config-mn -numvms 4
python ./run_tests.py -test deploy/rackhd_ha_install.py -config dellemc-test/config-mn -stack 4 -numvms 4
```
=> Rac 4090/ha deployment

test/tests/api/v2_0/nodes_tests.py
Relates to RAC-1984, https://github.com/RackHD/on-http/pull/551
Small PR returning a line of code that was removed from a test by mistake.
I made a mistake with a previous PR which removed three lines from this CIT test. The line added to the CIT test by this PR was originally in this test and exposes data which is used in later tests.
=> Adding back lines for CIT test

test/tests/redfish10/test_redfish10_api_taskservice.py, test/tests/redfish10/test_redfish10_system_reset_base.py
This PR revises two Redfish test scripts that still use API 1.1 to use API 2.0. These are the only non-API-1.1 scripts that needs revision for the imminent deprecation of API 1.1.
Both scripts have had references to API 1.1 revised to 2.0 and have had Hound violations fixed.
test_redfish10_system_reset_base.py used API 1.1 via a routine in common/test_api_utils.py which is entirely API 1.1. Erika and I decided that since this was the only reference to that library in the test harness, the easiest and most direct solution was to pull that one routine into the test file and convert to 2.0. 
The future of common/test_api_utils.py is still undetermined but it may be deprecated. If not, it needs a complete rewrite.
@hohene @jimturnquist @johren @larry-dean @stuart-stanley
=> Rac 4443 Revise API 1.1 to 2.0 in Redfish tests

test/common/fit_common.py
Resubmit of RAC-4289 with review changes:
•When rackhd_host is localhost it was always setting port to 8080. This is old code from the pre 'fit-config' days. I removed that code. Now the default port setting is pulled from the install_default.json config file.
•-http/-https arguments to force protocol were not working because of type mismatch from string to Boolean.
•I removed the automatic protocol selection code in rackhdapi(), which was an OnRack leftover that does not work any more in the RackHD world. This code was supposed to check to see if the http endpoints are available, if not then select https. The default protocol is now set to http. If https is desired, then use the -https parameter on the command line. I think that this is simpler and less error-prone than the automatic …
=> RAC-4289 FIT port/protocol selection bugs

test/deploy/rackhd_stack_init.py
Recent changes in API 2.0 broke the passive switch and PDU discovery in stack init. This has not affected the PR gate since they don't have switches or PDUs, but did cause errors in MN smoke test. This PR updates these routines and also the following technical debt:
- change print statements to FIT logging
- clean up Hound violations
@hohene @larry-dean @jimturnquist @stuart-stanley @RackHD/corecommitters
=> RAC-4348-rackhd_stack_init.py

test/tests/bootstrap/test_redfish10_os_bootstrap_parallel.py
This resubmit of the new test script that runs Redfish 1.0 OS bootstrap tests in parallel. This dramatically reduces test time from several hours down to 15-20 minutes, making this test suitable for regression suite.
This test allocates available nodes to test cases then runs all of them. 8 nodes are required to run all of the existing test cases. If there are less than 8 nodes, tests will be skipped. Note that Redfish API currently only supports ESXi, CentOS, and RHEL. Tests for other OSs will be added when Redfish API is updated.
Most of the work in this script is done in the classSetUp routine. The test methods are just polling loops to wait for completion of the associated workflow and assert on fail.
@hohene @jimturnquist @larry-dean @stuart-stanley @johren
=> Rac 4080 parallel OS bootstrap test

test/common/test_api_utils.py
This is an interim fix for the library file common/test_api_utils.py which was entirely API 1.1
This is a legacy library that is used infrequently but is called in the Smoke test tests/compute/test_rackhd20_computenode_pollers.py, so it needs immediate revision.
Here is the rundown of changes:
- replaced all API 1.1 to 2.0 and made necessary logic changes to support 2.0 JSON
- removed and redirected get_active_workflow() and delete_active_workflow() which was duplicated in fit_common check_active workflow() and cancel_active_workflow()
- Fixed Hound violations
Still to do:
- Change VERBOSITY logging to FIT logging
- Better error recovery
@hohene @stuart-stanley @jimturnquist @johren
=> Migrate common/test_api_utils.py from API 1.1 to 2.0

test/requirements.txt, test/run.py, test/tests/api/v2_0/lookups_tests.py, test/tests/api/v2_0/nodes_tests.py, test/tests/api/v2_0/obm_settings.py, test/tests/api/v2_0/sel_alert_poller_tests.py
As part of the disabling of the RackHD 1.1 API, we need to turn off the tests for the 1.1 API in CIT and FIT.
This PR will remove the tests from the CIT CI smoke-tests group.  additional PRs coming for FIT and on-build-config.
- removed the on-http 1.1 api from requirements.txt - so won't be build in the library
- removed api1.1 group from run.py
- updated node_tests.py to remove an outdated call to 1.1
Tested running against physical hardware and vagrant. 
Tested smoke-tests, api-redfish-1.0, and api-v2_0 groups. 
@tannoa2 @johren @panpan0000 @BillyAbildgaard @keedya @gpaulos
=> RAC-4397 - Remove RackHD api 1.1 calls from CIT smoke-tests

test/tests/ucs/test_rackhd_api_ucs.py
Change the /api/1.1/nodes call to /api/2.0/nodes
@tannoa2 @keedya @johren @gpaulos
=> RAC-4487 - test_rackhd_api_ucs - Remove api/1.1 reference, change to 2.0

test/.gitignore, test/mkcheck.sh, test/stream-monitor/flogging/infra_logging.py, test/stream-monitor/sm_plugin/__init__.py, test/stream-monitor/sm_plugin/stream_monitor.py, test/stream-monitor/stream_sources/__init__.py, test/stream-monitor/stream_sources/log_type.py, test/stream-monitor/stream_sources/monitor_abc.py, test/stream-monitor/stream_sources/self_test_source.py, test/stream-monitor/stream_sources/stream_matchers_base.py, test/stream-monitor/stream_sources/stream_matchers_results.py, test/stream-monitor/test/plugin_test_helper.py, test/stream-monitor/test/support/stream-base/one_pass/test_one_pass.py, test/stream-monitor/test/support/stream-source/logging/stderr_nocap/test_stderr_nocap.py, test/stream-monitor/test/support/stream-source/logging/stdout_errcap/test_stdout_errcap.py, test/stream-monitor/test/support/stream-source/logging/stdout_failcap/test_stdout_failcap.py, test/stream-monitor/test/support/stream-source/logging/stdout_nocap/test_stdout_nocap.py, test/stream-monitor/test/test_logopts.py, test/stream-monitor/test/test_matchers.py
This story was pre-dojo and is way too long. It is a good checkpoint of the asynch matching engine to date, however!
Primary feature chunks in here:
* Added the stream-monitor base plugin. This is the classes that specific stream monitors will be based on.
* Added a matcher engine (stream_matchers_base.py)
** ordered and unordered groups of matchers, along with a root group. The groups are the entry point for processing "events" and do a lot of the common logic.
** a StreamMatchBase that protocol-specific matchers will subclass to implement their special sauce. Handles a lot of common logic, leaving as little as possible to be done in the subclass. Mostly implementing '_match' to try and see if an event matches or not.
** a match-batch class to tie events to the results of various …
=> rac-261 stream monitor base matcher logic.

test/tests/amqp/test_amqp_poller_alert.py
This PR add FIT test for AMQP poller alert
1. SEL alert. Inject critical SEL entry in node BMC(CPU iERR) to generate a SEL alert event. RackHD is expected to send out AMQP message.
2. Generate a chassis power state change event. RackHD is expected to send out power state change AMQP alert.
=> Amqp poller alert

test/tests/amqp/test_amqp_node_rediscover.py
Add test for amqp message node discovery. This test will try remove one node and reboot it to generate a series of AMQP messages. Then it will wait for node get discovered and get the AMQP message.
WIP
=> Add test for amqp message node discovery

test/stream-monitor/flogging/infra_logging.py, test/stream-monitor/sm_plugin/stream_monitor.py, test/stream-monitor/stream_sources/log_type.py, test/stream-monitor/test/log_stream_helper.py, test/stream-monitor/test/plugin_test_helper.py, test/stream-monitor/test/test_log_stream.py, test/stream-monitor/test/test_log_stream_fmat.py, test/stream-monitor/test/test_logopts.py
This adds tests and code to include the following new data in each log-line:
* the logger name that originated the message, such as 'infra.run' and so-on
* the log-type stream-source's test-case-number (test_block.test_number), which is currently only in the special start/stop messages
* the test-name being executed.
Note that the test-name being part of every line unblocks the story to allow a user to say "turn up the logging on THIS test and this test ONLY to 11"...
Changes done to make this happen:
* added test-name, test-case-number, and name to infra-logging
* adjusted stream_monitor to callout to handle_before_test, handle_after_test, and made the callout method a common one that checks for the attribute before calling
* added the following to the log_type stream-source:
** added a …
=> rac-3775 need logger-name in log-line

packer/ansible/roles/rackhd-builds/tasks/aptitude_install_rackhd.yml, packer/ansible/roles/rackhd-builds/tasks/main.yml
This PR is for:
* Put the version check ahead of time (right after aptitude install)
* Ansible log is not enough. Should increase a bit
=> [skip ci]packer ansible: add rackhd install log and version check

test/tests/api/tmp_fit_staging/redfish_1_0/account_service_tests.py, test/tests/api/tmp_fit_staging/redfish_1_0/chassis_tests.py, test/tests/api/tmp_fit_staging/redfish_1_0/event_service_tests.py, test/tests/api/tmp_fit_staging/redfish_1_0/managers_tests.py, test/tests/api/tmp_fit_staging/redfish_1_0/registry_tests.py, test/tests/api/tmp_fit_staging/redfish_1_0/schema_tests.py, test/tests/api/tmp_fit_staging/redfish_1_0/session_service_tests.py, test/tests/api/tmp_fit_staging/redfish_1_0/systems_tests.py, test/tests/api/tmp_fit_staging/redfish_1_0/task_service_tests.py
This PR is for ttaging the CIT redfish_1_0 test scripts into a temp directory for follow on PRs.
This will allow for doing diffs between original and converted scripts, without losing the master.
The scripts in this PR are a copy of the scripts in /test/tests/api/redfish_1_0 only, no updates,
They won't run as part of the CIT or FIT smoke tests in this form.
Plan is:
1. copy the original scripts into this staging area  (this PR)
2. mv the staged script and apply the converted script on top do show the diffs only for review
3. allow the converted script to run in FIT smoke suite.
For this PR. please ignore the hound errors.  This PR is copying existing scripts into a staging directory, and the hound errors will be fixed when we apply the NEW converted scripts.
=> RAC-4182 - Staging the CIT redfish_1_0 test scripts into temp directory

test/requirements.txt, test/stream-monitor/flogging/logger_sets.py, test/stream-monitor/requirements.txt, test/stream-monitor/sm_plugin/__init__.py, test/stream-monitor/sm_plugin/stream_monitor.py, test/stream-monitor/stream_sources/__init__.py, test/stream-monitor/stream_sources/amqp_od/__init__.py, test/stream-monitor/stream_sources/amqp_od/amqp_on_demand.py, test/stream-monitor/stream_sources/amqp_od/rackhd_amqp_od.py, test/stream-monitor/stream_sources/amqp_source.py, test/stream-monitor/stream_sources/monitor_abc.py, test/stream-monitor/test/test_amqp_mon.py, test/tests/framework_tsts/test_amqp_stream_monitor.py
Added to stream-monitor-plugin:
* AMQP stream source
* On-demand amqp server
* plugin self-tests to:
* * send a msg and synchronously read it back
* * send a msg and let a greenlet receive the message (but then poll the greenlet)
* * send and log a msg
* added --sm-amqp-server option to allow FIT level tests to say where the AMQP server is
Signed-off-by: Erika Hohenstein <Erika.Hohenstein@dell.com>
This was done paired. @RackHD/corecommitters and specifically @johren 
Note: the added ability and self-tests are not "main line" tests yet.
=> RAC-4588 amqp stream monitor groundwork PR

test/util/display_SYSINFO_settings.py, test/util/display_node_FIRMWARE_versions.py, test/util/display_node_firmware_versions.py, test/util/display_rackhd_nodes.py, test/util/display_sysinfo_settings.py, test/util/node_list.py
This PR updates the test/utils files to be API 2.0 compliant. These are not tests and are not used in the PR gate. They are just convenience scripts for utility functions.
- migrated all API 1.1 to 2.0
- fixed Hound violations
- updated copyright notice
- added VERBOSITY = 1 to clean up report output
@hohene @jimturnquist @stuart-stanley @larry-dean @johren
=> Rac 4453 migrate utils to api2.0

test/tests/api/tmp_fit_staging/redfish_1_0/chassis_tests.py, test/tests/api/tmp_fit_staging/redfish_1_0/managers_tests.py, test/tests/api/tmp_fit_staging/redfish_1_0/systems_tests.py
First set of redfish CIT to FIT converted scripts for review.  chassis, system, management.
The tests aren't enabled yet in smoke, but I have 'enabled' and tested outside of this PR against vagrant and physical stacks.
This is part of step 2 in associated PR 673.
Plan is now:
1. copy the original scripts into this staging area (this PR)
2. apply the converted script on top do show the diffs only for review
3. mv the script and allow the converted script to run in FIT smoke suite.
@johren @dalebremner @brianparry @larry-dean @gpaulos @jimturnquist @keedya
=> RAC-4182 - Converted cit to fit format - redfish api scripts 

test/tests/api/tmp_fit_staging/redfish_1_0/event_service_tests.py, test/tests/api/tmp_fit_staging/redfish_1_0/schema_tests.py, test/tests/api/tmp_fit_staging/redfish_1_0/task_service_tests.py
Second set (of three) of redfish CIT to FIT converted scripts for review. 
- task_service_tests.py
- schema_tests.py
- event_service_tests.py
The tests aren't enabled yet in smoke, but I have 'enabled' and tested outside of this PR against vagrant and physical stacks.
This is part of step 2 in associated PR 673.
Plan is now:
1. copy the original scripts into this staging area (this PR)
2. apply the converted script on top do show the diffs only for review
3. mv the script and allow the converted script to run in FIT smoke suite.
@johren @dalebremner @brianparry @larry-dean @gpaulos @jimturnquist @keedya
=> RAC-4182 - Adding converted CIT redfish v1 scripts into staging.

test/tests/api/tmp_fit_staging/redfish_1_0/account_service_tests.py, test/tests/api/tmp_fit_staging/redfish_1_0/registry_tests.py, test/tests/api/tmp_fit_staging/redfish_1_0/session_service_tests.py
This PR is to convert the following three redfish scripts from CIT to FIT format.
Third set (of three).
- account_service_tests.py
- registry_tests.py
- session_service_tests.py
Tested against physical stacks and virtual stack.
This is part of step 2 in associated PR 673.
Plan is now:
1. copy the original scripts into this staging area (this PR)
2. apply the converted script on top do show the diffs only for review
3. mv the script and allow the converted script to run in FIT smoke suite.
@johren @dalebremner @brianparry @larry-dean @gpaulos @jimturnquist @keedya
=> RAC-4182 - Converted last three redfish scripts from CIT to FIT format in staging.

test/tests/api/v2_0/nodes_tests.py
Here is an API fix for nodes/:id/workflows - RackHD/on-http#613
It cannot pass because it causes a CIT test failure. That CIT test was made based on the APIs original flawed implementation.
This PR comments out the failing assert while also presenting the new CIT test in comments.
Ideally, this PR will be merged immediately followed by the above API fix followed by a final PR for the new CIT test being un-commented out.
=> Temporary removal of CIT test blocking an API fix

packer/HWIMO-BUILD, packer/add_IP_property_to_ova.sh
**background:**
originally, there's a feature in RackHD OVA which during deployment , we can specific the IP of the OVA, in a non-DHCP environment.
that make convenience for batch deployment for lots of RackHD OVA without manually setup IP.
But it turns out this feature only support by VMWare vCenter, not supported by vSphere.
Taken many user still use vSphere, so I have to make this advanced feature *not a default* one.
**What's Change:**
I didn't change anything from original line 217 - 295.
but just put them inside a "if" block.
and this "if" is by default false.
**Test Done**
1. Build:
use below command locally, and build successful
```
OS_VER=ubuntu-16.04   BUILD_TYPE=vmware   ANSIBLE_PLAYBOOK=rackhd_ci_builds   ./HWIMO-BUILD
```
2. Deploy ova(without customized property) to vSphere …
=> [Skip CI]by default, not to build OVA with customized property, which not supported by vSphere

test/tests/api/v2_0/nodes_tests.py
Correction for an earlier CIT test modification.
This should make CIT green for both master and this API fix - https://github.com/RackHD/on-http/pull/613
=> Correction for CIT test modification.

test/tests/api/v2_0/nodes_tests.py
This CIT test fails when run against the fix for GET node/:id/workflows (https://github.com/RackHD/on-http/pull/613)
The POST for node/id/workflows works with master and the above GET fix. However, the CIT test breaks and blocks the GET fix from getting merged. I propose that this test be temporarily removed so the GET API fix can be moved in. Meanwhile a new ticket will be added for correcting the CIT test for POST.
What I have in the pipes at the moment is this test removal, the API fix, and a new GET CIT test.
=> RAC-1984 (somewhat) Removal of node/:id/workflows POST CIT test

test/tests/api/v2_0/nodes_tests.py
Reverts RackHD/RackHD#707
The PR merge breaks the rule that freeze merge during sprint tag and sprint release and we have found this  merge causes the sprint release's version bumps fails due to following error
```
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart.
```
To not block this sprint release, the simplest solution is to revert this PR. 
@lacarb please reopen the original pull request or submit a new pull request after the sprint release.
=> Revert "RAC-1984 (somewhat) Removal of node/:id/workflows POST CIT test"

test/tests/api/v2_0/nodes_tests.py
This relates to #707. I did not consider that the PUT test would have the same issue as POST. They both use and fail when posting a workflow when the GET API fix is present.
This CIT test fails when run against the fix for GET node/:id/workflows (RackHD/on-http#613)
The PUT for node/id/workflows works with master and the above GET fix. However, the CIT test breaks and blocks the GET fix from getting merged. I propose that this test be temporarily removed so the GET API fix can be moved in. Meanwhile a new ticket will be added for correcting the CIT test for PUT.
What I have in the pipes at the moment is this test removal, the API fix, and a new GET CIT test.
=> RAC-1984 (somewhat) Removal of PUT node/id/workflows CIT test

example/README.md
@DavidjohnBlodgett @panpan0000 @RackHD/corecommitters 
More updates to the README to accurately reflect what steps are needed based on how things are currently structured in the vagrant box environment.  I do think it would be great to get back to the point where some of the steps (especially in regards to setting up the OS mirror) are no longer required manually.  Steps such as manually creating the ~/src directory and cloning the on-tools directory into there and setting up the on-http and on-tftp directories.
=> More updates to the README

test/common/fit_common.py, test/common/mkcfg.py, test/config/install_default.json, test/config/stack_config.json, test/tests/amqp/test_amqp_node_rediscover.py, test/tests/amqp/test_amqp_poller_alert.py, test/tests/amqp/test_amqp_racknode.py
Normalize the use of amqp with/without ssl.
Add logic that looks for file named deploy-generated.json in
the config directory.  If found, this file gets applied on
top of the configuration being generated.   This allows for a
given deployment to stamp out the ports, etc it needs without
having to make changes to stack_config.json.
@hohene @johren @stuart-stanley @gpaulos
=> RAC-4753, RAC-4752

test/tools/save-logs/README.md, test/tools/save-logs/extract_logs.py, test/tools/save-logs/rackhd_gather_info.py, test/tools/save-logs/save_logs.py, test/tools/save-logs/save_logs_conf.json.template
This utility will grab log files and status information from a rackhd server. 
The data is returned in the form of a gzipped tarball and can be extracted to a specified directory path and target directory.
We can add commands to run against the server and specify files to grab into the rackhd_gather_info.py script as we find more things we want.
This has been tested against rackhd servers installed via vagrant and installed on physical stacks source/package install.
To run against vagrant, I use:   python save_logs.py -ip 127.0.0.1 -user vagrant -pwd vagrant -port 2222 -target_dir mylog1
@johren @larry-dean @jimturnquist @panpan0000 @PengTian0 @gpaulos
=> RAC-180 - migrate the loggather utility from autotest to rackhd.

packer/scripts/cleanup.sh
In ```firstuser.sh``` after testing rackhd services, mongodb service was stopped.
so then in ```cleanup.sh``` 
```
vmware-iso: Cleaning up mongodb
vmware-iso: MongoDB shell version: 2.4.9
vmware-iso: connecting to: pxe
vmware-iso: exception: connect failed
vmware-iso: Fri Apr 14 04:55:32.242 Error: couldn't connect to server 127.0.0.1:27017 src/mongo/shell/mongo.js:145
```
Uncleaned mongodb may lead to various problems.
=> bugfix: failed to cleanup mongodb when packer build

test/common/fit_common.py, test/stream-monitor/requirements.txt, test/stream-monitor/sm_plugin/stream_monitor.py, test/stream-monitor/stream_sources/__init__.py, test/stream-monitor/stream_sources/amqp_source.py, test/stream-monitor/stream_sources/ssh_helper.py, test/tests/framework_tsts/test_amqp_stream_monitor.py
* Added ssh-helper inside plugin to be able to go on-box and add an amqp user.
* Wired handle_finalize call-all-sources and added a handler in amqp stream monitor to cause delete of amqp user
* Altered ports in install_default.json and stack_config.json get the amql_ssl port and ssh port correct for both on box (vagrant) and offbox (vagrant_remote) stack types.
* Altered nose-invoke in fit-common to add all the required ssh and amqp configure information to be passed into plugin.
Signed-off-by: Erika Hohenstein <Erika.Hohenstein@dell.com>
Note: the port names may have gotten stale, but if the PR gate passes, we can merge and rebase into the story Erika and I are on right now and fix there worse case. (i.e., no impact for anyone other than us)
@hohene @johren
=> RAC-4793 connect fit deployed amqp ports into amqp stream monitor

.gitignore, test/stream-monitor/flogging/infra_logging.py, test/stream-monitor/sm_plugin/stream_monitor.py, test/stream-monitor/stream_sources/amqp_od/amqp_on_demand.py, test/stream-monitor/stream_sources/amqp_od/rackhd_amqp_od.py, test/stream-monitor/stream_sources/amqp_source.py, test/stream-monitor/stream_sources/monitor_abc.py, test/stream-monitor/stream_sources/self_test_source.py, test/stream-monitor/stream_sources/stream_matchers_results.py, test/stream-monitor/test/log_stream_helper.py, test/stream-monitor/test/test_amqp_matchers.py, test/stream-monitor/test/test_amqp_tracker.py, test/tests/framework_tsts/test_amqp_stream_monitor.py
* pass in blank dns settings to rabbitmq docker instance (prevents timeouts if no dns available)
* added a retry loop in on-demand-amqp to allow container time to stabalize.
* changed 'log_facility' attribute as name of greenlet to 'greenlet_name' in flogging (log_facility was left over from orig code used as template)
* added mechanism ('handle_set_flogging') to allow sub-plugins to be updated with loggers
* removed 2nd call to handle_after_test on each sub-plugin. This was causing the test # to go up by two for each test.
* In log_stream_helper.py
** taught check code to ignore logs messages coming -from- the plugin infrastructure
** altered diag info in asserts to be more useful
* in monitor_abc.py:
** converted to gevent.queue.Queue for inject-to-finish transport (allows self-test …
=> RAC-4794-wiring-match-all-amqp-matcher-engine

test/run.py
This will stop it from running as part of the PR gate.
The redfish scripts have been convert to the FIT format and exist in the directory /test/tests/api-cit/redfish_1.0 and are running as part of the PR gate under the 'FIT' bubble.
=> Removing the redfish_1.0 group from the CIT smoke-test suite.

test/Vagrantfile, test/requirements.txt, test/stream-monitor/requirements.txt, test/stream-monitor/stream_sources/amqp_od/rackhd_amqp_od.py, test/stream-monitor/stream_sources/amqp_source.py, test/stream-monitor/stream_sources/ssh_helper.py, test/stream-monitor/stream_sources/stream_matchers_base.py, test/stream-monitor/test/test_amqp_matchers.py, test/stream-monitor/test/test_amqp_tracker.py, test/tests/amqp/test_amqp_heartbeat.py, test/tests/framework_tsts/test_amqp_stream_monitor.py
* alterations to amqp_source.py to handle first real use-case
** have it decode body's json string
** rename get_tracker_processor to get_tracker_queue_processor (and change all references to it in test_amqp_matchers)
** rename "match_any" to match_any_event (and change all refs to it in test_amqp_matchers)
** add commandline options to allow test-writer to NOT have to wait through setting up and tearing down a test user each time: intended use time is DURING fast iterations used in test dev.
*** new option to created a user by name
*** new option to use an existing user by name
** changed failed delete of automatic test user to a warning (case in OVA install where rabbitmqctl goes -away- because of the "test")
** added route-key based match-clause to _AMQPMatcher
** fixed main …
=> RAC-4796 first stab of actual amqp matcher

test/tests/bootstrap/test_api20_os_bootstrap_parallel_proxy.py
This script implements 'parallel' OS install via proxy using API 2.0 commands. As with the Redfish proxy test, the script harvests test repo information from the config.json 'http-proxies' section then runs a minimum-payload installation test on each.  This test script is suitable for use in PR gate because it uses minimum resources and executes in under 20 minutes.
To run all tests, a stack must contain 11 nodes, virtual or physical but can be run with fewer. As with the proxy-based tests, this test will skip any test where there are insufficient nodes to run or where appropriate repo info is not present in config.json.
This test does NOT contain a Windows OS install which cannot be performed via proxy.
This test is NOT tagged to run under Smoke or Regression runs and must be executed at …
=> Rac 4327 Parallel API 2.0 OS install test for proxy repos

docker/dhcp/config/dhcpd.conf
1. ubuntu os installation need dns-server configuration.
2. change INTERFACES to em1 for test stack.
This PR just fix this issue in our CD system.
However, how to do this configuration for users is still a issue.
@panpan0000
=> docker: add dns for ubuntu os install, 

test/deploy/rackhd_stack_init.py, test/modules/auth2_0.py, test/modules/redfish_auth.py, test/tests/api-cit/redfish_1_0/event_service_tests.py, test/tests/api/redfish_1_0/event_service_tests.py
Some cases simulate the practical application scene,
it ssh login to rackhd and do something to localhost.
In pr gate, rackhd is hosted in vagrant box, so ssh login with user/password to rackhd is vaild.
However, rackhd and tests run in different machine is just one application scenario.
There may be other scenarios that rackhd and tests must run in one machine. and in this situation ssh is not necessary, user/password management will be complicated too.
This PR modified some cases.
1st it will try to do things to rackhd directly.
if failed,
it will ssh login && do something.
@panpan0000 @PengTian0 @iceiilin
=> modify some cases to support local rackhd

packer/HWIMO-BUILD, packer/README.md, packer/ansible/rackhd_ci_builds_mini.yml, packer/ansible/rackhd_local_mini.yml, packer/ansible/rackhd_packer_mini.yml, packer/ansible/rackhd_prepare.yml, packer/ansible/rackhd_release_mini.yml, packer/scripts/cleanup.sh, packer/scripts/dep.sh, packer/template-ubuntu-14.04.json, packer/template-ubuntu-16.04.json
**Background**
more detail in RAC-4360
PPT in https://rackhd.atlassian.net/wiki/display/RAC1/RackHD+CI%3A+packer+build+enhancement+oppotunity
the OVA packer build is too long for 1 hour. but in 80% time, the actions are the same for each build.
so we use 2-way packer build 
(1) build a template VMX which OS installed and all RackHD dependency installed
(2) install specific version of RackHD deb into above VMX, then pack to OVA
vagrant-box is in the similar way.
----
**detail in code**
HWIMO-BUILD: use "BUILD_STAGE " to select which way to go.
-BUILD_TEMPLATE : it build the template cached VMX. 
-BUILD_FINAL:  based from the cached VMX, build the final OVA
-BUILD_ALL:  it includes above 2 steps  (NOTE: it requires VMWare Workstation licensed version)
original packer ansible playbooks are …
=> Cached OVA from a Pre-Build VMX

test/tests/bootstrap/test_api20_linux_bootstrap.py
New API 2.0 FIT OS bootstrap test for Linux distros. Payload can be specified by loading a file using the -extra parameter. Examples in the file header comments.
There is a default payload for CentOS 7, but the repo spec is, as always, site specific. There is no generic repo spec that will work in all situations unless some conventions are adopted. Erika and I are unsure whether there should be a default payload at all. Any thoughts?
This is the base test script. It is intended to be enhanced with additional tests to verify payload parameters in future stories. 
@hohene @johren @derrickostertag @stuart-stanley @jimturnquist
=> API 2.0 FIT OS bootstrap test for Linux distros

test/tests/api/v2_0/sel_alert_poller_tests.py
The test process is like this: 
clear sel and add sel entry -> get sel ID1 -> clear sel and add sel entry -> get sel ID2 -> compare whether ID2 = ID1 + 1
It's a BMC function, and from local single vNode test, ID2 = ID1 + 2, which is align with IPMI standard. So remove it here in CIT.
@hohene @tannoa2
=> remove sel overflow test case in CIT since it tests BMC function only

packer/ansible/rackhd_local.yml, packer/ansible/roles/mongodb/files/mongodb.conf, packer/ansible/roles/mongodb/tasks/main.yml, packer/ansible/roles/remoterepos/tasks/main.yml
Move some actions in vagrant up to packer build.
1. Add pip install ucs-service/requirments.text
2. Add mongo conf.
3. Build with virtualbox 5.0.32
=> modify packer script for vagrant 0.17

test/tests/api/fit-staging/v2_0/nodes_tests.py, test/tests/api/fit-staging/v2_0/obm_settings.py, test/tests/api/fit-staging/v2_0/obm_tests.py
One set of converted cit to fit scripts 
Converted scripts include:
removing proboscis from the scripts and updating to the unittest format
updating the style to meet flake8 checks
fixed scripts to operate properly against specific node types -compute, switch, pdu
fixed scripts to clean up added test nodes
These tests won't run in smoke until we move then to api-cit directory. 
@johren @larry-dean @brianparry @dalebremner @keedya @srinia6
=> Rac 4181 apiv20 converts - nodes_tests.py, obm_settings.py, obm_tests.py

test/tests/bootstrap/test_api20_esxi_bootstrap.py
New API 2.0 FIT OS bootstrap test for ESXi. Payload can be specified by loading a file using the -extra parameter. Examples in the file header comments.
There is a default payload for ESXi 6, but the repo spec is, as always, site specific. There is no generic repo spec that will work in all situations unless some conventions are adopted. 
This is the base test script. It is intended to be enhanced with additional tests to verify payload parameters in future stories.
Paired with Larry Dean.
@hohene @johren @larry-dean
=> API 2.0 FIT OS bootstrap test for ESXi

test/tests/bootstrap/test_api20_linux_bootstrap.py
Found a math problem with the workflow timer in the Linux OS install test. We had the expression backwards and the timer wasn't timing out. 
Single line fix.
@hohene @johren
=> Fix start_time bug in Linux OS Install

test/config/stack_config.json
This is a temporary fix for https://rackhd.atlassian.net/browse/RAC-5184.  The Docker and OVA tests are failing the UCS tests because the UCS-service is not included in either of these builds.  This change will disable the UCS tests.  They will be re-enabled once the UCS-service is include in the RackHD Docker and OVA builds.  
=> remove ucsm-ip to disable UCS tests

packer/template-ubuntu-14.04.json, packer/template-ubuntu-16.04.json
**Why skip CI**
current PR Gate won't involve the packer build step
**Why this change**
Originally modified with this PR: https://github.com/RackHD/RackHD/commit/51121591a200c78c66f98075143cc65677685967
But accidentally,  it was overwritten with this PR: https://github.com/RackHD/RackHD/commit/5ba383d4bce6695ef1767d6b7fd612c961ddea54 
@keedya  @iceiilin @anhou @PengTian0
=> [Skip CI] RAC-5200 restore back OVA mem size from 1G to 4G

test/tests/bootstrap/test_api20_windows_bootstrap.py
Windows OS Install FIT test script for arbitrary payloads.
The Windows OS install requires additional configuration of the RackHD server as outlined in the header notes.
Payload can be specified by loading a file using the -extra parameter. Examples in the file header comments.
There is a default payload for Windows 2012 but the repo spec is, as always, site specific. There is no generic repo spec that will work in all situations unless some conventions are adopted.
The default payload contains a dummy activation key. We cannot publish this script with a valid activation key. If the default payload is used, Windows Install will ask for a valid key on the console, which will continue if entered manually.. If fully automated operation is required, then a valid activation key must be …
=> RAC-5000 Windows OS Install test script

test/config/stack_config.json
Signed-off-by: Kranti Uppala <k.uppala@>
@RackHD/corecommitters @RackHD/veyron 
UCS tests pass on OVA and FIT builds in sandbox:  http://10.240.19.232:8080/blue/organizations/jenkins/MasterCI/detail/MasterCI/237/pipeline
=> re-enable UCS FIT Tests

test/config/install_esxi6.0_minimum.json, test/config/install_ubuntu14.04_minimum.json
These are the OS install payloads only for ESXi and Ubuntu. These are prerequisites for the test code and can be merged now. 
@johren @patelb10
=> RAC-5043,RAC-5060 Minimum OS install Payloads for ESXi and Ubuntu

test/config/stack_config.json, test/tests/rackhd20/test_rackhd20_api_notifications.py
Updated the stack-config.json file with additional stacks.
Added docker, ova, and vagrant_ucs test stacks.
This allows us to configure the test beds differently for the deployments and run tests using proper setup.
Also allows easier skipping of tests, if we need, if not running in an expected deployment.
updates to on-build-config in separate PRs.
=> RAC-4965 - add additional stack configurations for running pipelines

test/common/env_ip_helpers.py, test/common/fit_common.py, test/requirements.txt, test/stream-monitor/stream_sources/amqp_source.py, test/stream-monitor/stream_sources/monitor_abc.py, test/stream-monitor/stream_sources/self_test_source.py, test/stream-monitor/stream_sources/stream_matchers_base.py, test/stream-monitor/stream_sources/stream_matchers_results.py, test/stream-monitor/test/test_matchers.py, test/tests/amqp/test_amqp_heartbeat.py, test/tests/amqp/test_amqp_node_rediscover.py
* Common-changes:
** remote-shell was not honoring the ssh-port. Changed the code to do so AND include that in the check for a truly local command
* Added requirements.txt items:
** updated kombu to latest (matches plugin!)
** added ipaddress and netifaces to help making detection of actual test-host IP address even possible
* monitor base-class changes:
** threaded logging throughout
** threaded in "allow complete miss" logic
* stream_matchers_base and monitor_abc
** taught add_result recorder to understand lists
** enhanced is_empty to check -into- a list of results and call it empty if it is just a list of empties.
** threaded logging in
** added __str__ to a number of items to make diag easier
** added an _validate step. _match still handles "does this apply?" while _validate handles …
=> RAC-4994-amqp-rediscovery-conversion

test/config/stack_config.json
Removed UCS params from stack config to enable OS installs.
@johren @hohene @patelb10
=> RAC-5040 Removed UCS from 'vagrant' stack

test/config/imageservice_config.json
The code change is made due to the fact that in image service code, the southbound port is changed to 8060 in avoidance with vagrant testing environment.
https://github.com/RackHD/image-service/pull/7
@iceiilin @nortonluo @changev @pengz1
=> Change the southbound API port to 8060 and fix the CRLF

test/tests/bootstrap/test_api20_esxi_bootstrap.py
This PR increased ESXi OS install timeout to 45 minutes from 30. After this is merged we need to retest #210.
@johren @patelb10
=> RAC-5043 increase ESXi timeout to 45 min

packer/HWIMO-BUILD
**Why Skip CI**
current PR Gate can't verify packer build, so skip it.
will add PR Gate packer build sooner :-P
**Test**
pass unit-test 
when ```BUILD_STAGE=BUILD_ALL BUILD_TYPE=vmware  ./HWIMO-BUILD```
```
packer build --force --only=vmware-iso --var-file=template.cfg template-ubuntu-14.04.json.tmp
packer build --force --only=vmware-vmx --var-file=template.cfg --var playbook=rackhd_local_mini template-ubuntu-14.04.json.tmp
```
when ```BUILD_STAGE=BUILD_ALL BUILD_TYPE=virtualbox./HWIMO-BUILD```
```
+ packer2 build --force --only=virtualbox-iso --var-file=template.cfg template-ubuntu-14.04.json.tmp
+ packer2 build --force --only=virtualbox-ovf --var-file=template.cfg --var playbook=rackhd_local_mini template-ubuntu-14.04.json.tmp
```
**Reviewer**
@hohene  @anhou @iceiilin
=> [Skip CI]Fix RAC-5160: when BUILD_STAGE=BUILD_ALL, build from scratch

test/tests/bootstrap/test_api20_linux_bootstrap.py
This PR increased Linux OS install timeout to 45 minutes from 30. After this is merged we need to retest #210.
@johren @patelb10
=> RAC-5043 increase Linux OS install timeout

test/tests/ucs/test_rackhd_api_ucs.py
I'm running FIT with docker and sometimes the case "test_api_20_ucs_discover_and_catalog_all" failed with message: timeout for 180s.
Actually, the graph "ucs discovery" is succeed.
But the graph takes about 187s and the test case only waits for 180s.
@geoff-reid  @anhou @iceiilin @panpan0000
=> Fix: timeout to run test_api_20_ucs_discover_and_catalog_all

test/deploy/rackhd_stack_init.py, test/tests/ucs/test_rackhd_api_ucs.py
Several changes to UCS tests to improve reliability
1)  Move UCSPE initialization from state_init to main tests.
2)  If we cannot access UCSPE skip all UCS tests instead of failing
3)  UCSPE initialization will now wait for config to be valid
=> update ucs tests to fix occasional failures

test/config/imageservice_config.json
As PR-Gate and Master CI are using virtual machines instead of physical stack for testing, the directory where the static files are stores are /home/vagrant/src/on-http/common instead of /var/renasar/on-http/static/common, change the configuration code accordingly. Note: further change might be required when using docker or all-in-one solution.
=> modify the image service test configuration to suite testing env

test/tests/api-cit/v2_0/workflowTasks_tests.py, test/tests/api/v2_0/workflowTasks_tests.py
The test job for "replacing vagrant with docker" is failed at case : "workflowTasks_tests.WorkflowTasksTests.test_workflowTasks_put".
The failure rate of the case is 1/155
Link of the failed link: http://rackhdci.lss.emc.com/job/DockerTest/150/
Root cause:
The test case adds a task to the database taskdefinitions, then get all the task definitions and check whether the last one is just the added one.
But the result of "getting all the task definitions" is not sorted, so sometimes the case failed.
@anhou @iceiilin @panpan0000
=> Fix: Failed testing WorkflowTasksTests.test_workflowTasks_put

test/tests/rackhd20/test_rackhd20_api_notifications.py
This PR turned back on test_rackhd20_api_notifications test on vagrant base stack
=> RAC-4965 Turned back on test_rackhd20_api_notifications to smoke test

docker/monorail/config.json, packer/ansible/roles/monorail/files/config.json, test/config/rackhd_default.json
Add autoCreateObm:true to config.json to utilize the modern OBM generation routine.
After this is merged, then the 'appy OBM settings' routine will be removed from stack init.
Paired with Beena
@jimturnquist @patelb10 @hohene
=> RAC-4091 Add autoCreateObm:true to all instances of config.json

test/deploy/rackhd_stack_init.py
This PR is followup on 
https://github.com/RackHD/RackHD/pull/822
we added utility autoCreateObm:true  in config file. This will remove test of apply obm setting from stack_init
=> RAC-4091 remove test of obmsetting from rackhd_stack_init.py

test/tests/redfish10/test_redfish10_api_systems.py
We have determined that an empty SEL 'message' field is normal under certain circumstances. Test was asserting on an empty message, which is a false failure.
In the event of an empty SEL 'message' field, the test will now issue an INFO message containing SensorType and SensorNumber rather than an assert.
=> RAC-5603 update sel logs test to exclude empty 'message' field

test/config/credentials_default.json
Add docker hub dummy credentials in credentials_default.json
@manfrednde @jimturnquist
=> RAC-5635: Add docker hub dummy credentials

test/config/install_ubuntu14.04_maximum_QuantaT41.json
Submitting Ubuntu max payload with NIC parameters omitted. Found bug RAC-5684 in Ubuntu NIC parameters, so this is the maximum working payload as of submission date.
=> RAC-5607 Ubuntu maximum OS install payload

test/tests/imageserver/test_image_service_system.py, test/tests/imageserver/test_microkernel_image_service.py, test/tests/imageserver/test_os_image_service.py
Before the  code change, it took nearly half an hour to download on-http static files from the website. With the code change, the time is reduced to around 700s.  Also the cases with problem is fixed in the PR. @nortonluo
=> Use wget to download the files to speed up tests

test/tests/redfish10/test_redfish10_api_systems.py
* Correct tests to allow ethernetinterfaces for non-dell devices
=> RAC-5682 - Redfish Compliance, correct systems/ethernetinterface odata links for non-dell

docker/dell/config/gateway.yml
This gateway change is required for RAC-5348
=> new gateway route for inventory service v2.0 endpoint

test/common/fit_common.py, test/tests/bootstrap/test_api20_esxi_bootstrap.py
Here is sample output with the added debug info:
```
(fit)ndetau@lab01:~/Dev/rac-5835/RackHD/test$ ./run_tests.py -stack 14 -config config-mn -test tests/bootstrap/test_api20_esxi_bootstrap.py -nodeid 5988bd64df3287057100f6b6 
*** Using config file path: config-mn
*** Created config file: config-mn/generated/fit-config-20170810-183007
*** Using config file: config-mn/generated/fit-config-20170810-183007
2017-08-10 18:30:08,940 INFO    removing previous logging dir /emc/ndetau/Dev/rac-5835/RackHD/test/log_output/run_2017-08-10_16:53:59.d infra.run **.** 19499 MainProcess stream-monitor/flogging/infra_logging.py:__init__@148 gl-main [any tests]
2017-08-10 18:30:08,941 INFO    this runs logging dir /emc/ndetau/Dev/rac-5835/RackHD/test/log_output/run_2017-08-10_18:30:08.d infra.run **.** …
```
=> RAC-5835 Add more debug info for workflow

test/tests/bootstrap/test_api20_linux_bootstrap.py, test/tests/bootstrap/test_api20_windows_bootstrap.py
Error sample: 
(fit)ndetau@lab01:~/Dev/rack-5835-3/rackhd/test$ ./run_tests.py -stack 14 -config config-mn -test tests/bootstrap/test_api20_windows_bootstrap.py -nodeid 5988bd64df3287057100f6b6
*** Using config file path: config-mn
*** Created config file: config-mn/generated/fit-config-20170810-221041
*** Using config file: config-mn/generated/fit-config-20170810-221041
2017-08-10 22:10:42,859 INFO    this runs logging dir /emc/ndetau/Dev/rack-5835-3/rackhd/test/log_output/run_2017-08-10_22:10:42.d infra.run **.** 24873 MainProcess stream-monitor/flogging/infra_logging.py:__init__@148 gl-main [any tests]
2017-08-10 22:10:42,862 INFO     Start Of Test Block: 1                                                                    root 
*** Reloading config file: …
=> RAC-5917 Added more debug info for workflow

.gitignore, test/classes/user.py, test/tests/security/test_api_security_passwd_resets.py
RAC-4832: RackHD password reset tests
AutoTest refactored for Fit
Tests the ability for each user type (Admin, ReadOnly, Operator) to change/reset their password based on their permissions.
=> RAC-4832: RackHD password reset tests

docker/monorail/config.json, packer/ansible/roles/monorail/files/config.json, test/config/rackhd_default.json
This PR will switch the apiiServerPort back to 9080, which is the southbound port for on-http. 
@RackHD/committers
=> restore apiServerPort back to 9080 to use on-http southbound interface

test/runFIT.sh
The script runFIT.sh will be used by docker, ova, source_code and so on.
The step to replacing 172.31.128.1 with 172.31.128.250 is not needed by ova.
So the PR removes it
@panpan0000 @anhou @iceiilin
=> Fix: the step replacing 172.31.128.1 with 172.31.128.250 is not needed by ova

test/common/fit_common.py, test/deploy/rackhd_stack_init.py
Add update to test04_power_nodes_on.
If nodes are already present in the nodes list, don't perform a power cycle.
Assuming the nodes are then in a discovery process and following test will wait for the active workflows to complete.
paired with Derrick Ostertag.
=> RAC-5979 - updates to rackhd_stack_init.py

test/tests/redfish10/test_redfish10_api_taskservice.py
This change in FIT test is required for on-http PR:
https://github.com/RackHD/on-http/pull/750
This PR needs to be merged first to fix test error.
@derrickostertag @jimturnquist
=> FIT test fix for RAC-5913

example/Vagrantfile, example/dev-env-setup/roles/build/tasks/main.yml
**Background**
The manual's walkthrough of rackhd with a vagrant box makes extensive use of 'jq', which isn't actually installed. The jq package should be added in vagrant-based demo and dev environment.
**Reviewers**
@iceiilin @pengz1 @anhou
=> [RAC-5894] Fix the bug:vagrant without jq

docker/.env
With this modification, the community user will build and use docker images with devel tag.
=> RAC-5949 change docker-compose build default tag from latest to devel

packer/build_ova.sh
if running OVA cache build, there's no output-vmware-vmx folder , so ovftool at the post-process function will fail.
this PR is a hot fix.
Test pass:
http://rackhd.ci.xxxxx/job/OVA_CACHE_BUILD/174
=> HotFix for OVA Cache Build.

test/stream-monitor/stream_sources/amqp_source.py
There are some debug messages in early AMQP that are only usefull if debugging the amqp code itself. Set their debug level to 8 (not normally visible)
Do not merge until the deliberate test failure is removed!
=> rac-6421-turndown-some-amqp-debug

test/config/install_coreos_minimum.json, test/config/stack_config.json, test/deploy/rackhd_stack_init_baremetal.py, test/tests/api-cit/redfish_1_0/systems_tests.py, test/tests/api-cit/v2_0/sel_alert_poller_tests.py, test/tests/redfish10/test_redfish10_system_reset_base.py
Updates for bare-metal regression stacks.
- added separate init script rackhd_stack_init_baremetal.py
- verifies the hardware inventory before smoke starts
- skips any power on reset of the nodes before smoke starts
- update sel_alert_poller_tests to skip performing full SEL injection tests against real hardware
- update system tests to skip power-reset type tests
- updated coreos repository in install_coreos_minimum.json
- added stackType and stack_nodes into stack_config.json for running manually
=> Updates to support running smoke against real hardware

docker/dell/docker-compose.yml
**Background**
smi-service API could be invoked through each individual smi-service or smi-service-gateway which could be controlled by config file. During development of previous stories, we found it was failed to invoke API through gateway but successful through individual smi-services. We need to resolve this problem.
https://rackhd.atlassian.net/browse/RAC-6424
**Done**
Add extra_hosts: service-registry for consul.
**Reviewers**
@rahmanmuhamad  @RackHD/corecommitters @nortonluo
=> Fix the issue of visiting SMI firmware update service

test/config/stack_config.json, test/tests/ucs/test_ucs_api.py
1. Add ucs option to "docker_local_run" which is the stack used to run FIT.
2. Fix error : the api /catalog?identifier=switch-B is not supported.
@pengz1 @anhou @geoff-reid @tannoa2
=> RAC-6412: fix original FIT test cases for ucs-service

docker/dell/config/gateway.yml
**Background**
Based on the previous investigation result, develop to port Graph.Dell.Racadm.ResetComponents and /Systems/{identifier}/Bios.ResetBios to use WSMAN API.
https://rackhd.atlassian.net/browse/RAC-6481
We use `/api/1.0/server/configuration/systemErase` from SMI services to reset components.
**Done**
add systemErase for simConfig.json
@rahmanmuhamad @RackHD/corecommitters @nortonluo
=> add systemErase for simConfig.json

test/config/ucs.json, test/tests/ucs/ucs_common.py
The PR reads user account and physical nodes count from config file.
Because these info of ucs baremetal are different with ucs simulator.
@anhou @keedya @geoff-reid
=> RAC-6415: get account of ucs manager and physical nodes from config

test/tests/ucs/test_rackhd20_ucs_redfish_api.py, test/tests/ucs/ucs_common.py
**Background**
Some Redfish is created for UCS servers, FIT should include test cases for UCS Redfish APIs.
**Details**
1. All existing UCS Redfish APIs are tested
2. Redfish data are validate against non-empty items.
@bbcyyb @mcGG @PengTian0 @anhou
=>  Add redfish API test cases for UCS

docker/dell/config/gateway.yml
WSMAN powerthermal poller could not get correct poller data which is partially fixed in the PR https://github.com/RackHD/RackHD/pull/925.
Here is to update the path in SMI gateway routes.
https://rackhd.atlassian.net/browse/RAC-6694
@RackHD/corecommitters @iceiilin @nortonluo
=> fix WSMAN powerthermal poller issue
